In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/customer_churn.csv')

In [ ]:
df.head()

Empty DataFrame
Columns: [{"cells":[{"cell_type":"markdown", id:"stretch-davis", metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935", papermill:{"duration":0.04692, end_time:"2021-05-07T08:35:59.190175", exception:false, start_time:"2021-05-07T08:35:59.143255", status:"completed"}, tags:[]}, source:["<center>\n", <img src=\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\">\n",     \n, ## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course \n, \n, Author: [Yury Kashnitsky](https://yorko.github.io). Translated and edited by [Christina Butsko](https://www.linkedin.com/in/christinabutsko/), [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina), Sergey Isaev, and [Artem Trunov](https://www.linkedin.com/in/datamove/). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.]}, {"cell_type":"markdown", id:"afraid-serum", metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668", papermill:{"duration":0.04455, end_time:"2021-05-07T08:35:59.279099", exception:false.1, start_time:"2021-05-07T08:35:59.234549", status:"completed"}.1, tags:[]}.1, source:["# <center> Topic 1. Exploratory data analysis with Pandas\n", \n.1, <img align=\center\" src=\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\"  width=50% />\n", \n.2, ## Article outline\n, 1. [Demonstration of main Pandas methods](#1.-Demonstration-of-main-Pandas-methods)\n, 2. [First attempt at predicting telecom churn](#2.-First-attempt-at-predicting-telecom-churn)\n, 3. [Assignments](#3.-Assignments)\n, 4. [Useful resources](#4.-Useful-resources)]}, {"cell_type":"markdown".1, id:"optional-comparative", metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649", papermill:{"duration":0.043036, end_time:"2021-05-07T08:35:59.367136", exception:false.2, start_time:"2021-05-07T08:35:59.3241", status:"completed"}.2, tags:[]}.2, source:["## 1. Demonstration of main Pandas methods\n", Well... There are dozens of cool tutorials on Pandas and visual data analysis. If you are already familiar with these topics, you can wait for the 3rd article in the series, where we get into machine learning.  \n, \n.3, **[Pandas](http://pandas.pydata.org)** is a Python library that provides extensive means for data analysis. Data scientists often work with data stored in table formats like `.csv`, `.tsv`, or `.xlsx`. Pandas makes it very convenient to load, process, and analyze such tabular data using SQL-like queries. In conjunction with `Matplotlib` and `Seaborn`, `Pandas` provides a wide range of opportunities for visual analysis of tabular data.\n, \n.4, The main data structures in `Pandas` are implemented with **Series** and **DataFrame** classes. The former is a one-dimensional indexed array of some fixed data type. The latter is a two-dimensional data structure - a table - where each column contains data of the same type. You can see it as a dictionary of `Series` instances. `DataFrames` are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.]}, {"cell_type":"code", execution_count:1, id:"supreme-beatles", metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4", execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z", iopub.status.busy:"2021-05-07T08:35:59.458289Z", iopub.status.idle:"2021-05-07T08:35:59.462927Z", shell.execute_reply:"2021-05-07T08:35:59.46356Z"}, papermill:{"duration":0.052221, end_time:"2021-05-07T08:35:59.463863", exception:false.3, start_time:"2021-05-07T08:35:59.411642", status:"completed"}.3, tags:[]}.3, outputs:[], source:["import numpy as np\n", import pandas as pd\n, \n.5, pd.set_option(\display.precision\",  2)"]}, {"cell_type":"markdown".2, id:"catholic-remainder", metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b", papermill:{"duration":0.045851, end_time:"2021-05-07T08:35:59.553832", exception:false.4, start_time:"2021-05-07T08:35:59.507981", status:"completed"}.4, tags:[]}.4, source:["We'll demonstrate the main methods in action by analyzing a [dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383) on the churn rate of telecom operator clients. Let's read the data (using `read_csv`),  and take a look at the first 5 lines using the `head` method:"]}, {"cell_type":"code".1, execution_count:2, id:"interesting-dodge", metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7", execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z", iopub.status.busy:"2021-05-07T08:35:59.645658Z", iopub.status.idle:"2021-05-07T08:35:59.731091Z", shell.execute_reply:"2021-05-07T08:35:59.731563Z"}, papermill:{"duration":0.13323, end_time:"2021-05-07T08:35:59.731738", exception:false.5, start_time:"2021-05-07T08:35:59.598508", status:"completed"}.5, tags:[]}.5, outputs:[{"data":{"text/html":["<div>\n", <style scoped>\n,     .dataframe tbody tr th:only-of-type {\n,         vertical-align: middle;\n,     }\n, \n.6,     .dataframe tbody tr th {\n, ...]
Index: []

[0 rows x 4452 columns]

In [ ]:
df.tail()

Empty DataFrame
Columns: [{"cells":[{"cell_type":"markdown", id:"stretch-davis", metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935", papermill:{"duration":0.04692, end_time:"2021-05-07T08:35:59.190175", exception:false, start_time:"2021-05-07T08:35:59.143255", status:"completed"}, tags:[]}, source:["<center>\n", <img src=\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\">\n",     \n, ## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course \n, \n, Author: [Yury Kashnitsky](https://yorko.github.io). Translated and edited by [Christina Butsko](https://www.linkedin.com/in/christinabutsko/), [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina), Sergey Isaev, and [Artem Trunov](https://www.linkedin.com/in/datamove/). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.]}, {"cell_type":"markdown", id:"afraid-serum", metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668", papermill:{"duration":0.04455, end_time:"2021-05-07T08:35:59.279099", exception:false.1, start_time:"2021-05-07T08:35:59.234549", status:"completed"}.1, tags:[]}.1, source:["# <center> Topic 1. Exploratory data analysis with Pandas\n", \n.1, <img align=\center\" src=\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\"  width=50% />\n", \n.2, ## Article outline\n, 1. [Demonstration of main Pandas methods](#1.-Demonstration-of-main-Pandas-methods)\n, 2. [First attempt at predicting telecom churn](#2.-First-attempt-at-predicting-telecom-churn)\n, 3. [Assignments](#3.-Assignments)\n, 4. [Useful resources](#4.-Useful-resources)]}, {"cell_type":"markdown".1, id:"optional-comparative", metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649", papermill:{"duration":0.043036, end_time:"2021-05-07T08:35:59.367136", exception:false.2, start_time:"2021-05-07T08:35:59.3241", status:"completed"}.2, tags:[]}.2, source:["## 1. Demonstration of main Pandas methods\n", Well... There are dozens of cool tutorials on Pandas and visual data analysis. If you are already familiar with these topics, you can wait for the 3rd article in the series, where we get into machine learning.  \n, \n.3, **[Pandas](http://pandas.pydata.org)** is a Python library that provides extensive means for data analysis. Data scientists often work with data stored in table formats like `.csv`, `.tsv`, or `.xlsx`. Pandas makes it very convenient to load, process, and analyze such tabular data using SQL-like queries. In conjunction with `Matplotlib` and `Seaborn`, `Pandas` provides a wide range of opportunities for visual analysis of tabular data.\n, \n.4, The main data structures in `Pandas` are implemented with **Series** and **DataFrame** classes. The former is a one-dimensional indexed array of some fixed data type. The latter is a two-dimensional data structure - a table - where each column contains data of the same type. You can see it as a dictionary of `Series` instances. `DataFrames` are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.]}, {"cell_type":"code", execution_count:1, id:"supreme-beatles", metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4", execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z", iopub.status.busy:"2021-05-07T08:35:59.458289Z", iopub.status.idle:"2021-05-07T08:35:59.462927Z", shell.execute_reply:"2021-05-07T08:35:59.46356Z"}, papermill:{"duration":0.052221, end_time:"2021-05-07T08:35:59.463863", exception:false.3, start_time:"2021-05-07T08:35:59.411642", status:"completed"}.3, tags:[]}.3, outputs:[], source:["import numpy as np\n", import pandas as pd\n, \n.5, pd.set_option(\display.precision\",  2)"]}, {"cell_type":"markdown".2, id:"catholic-remainder", metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b", papermill:{"duration":0.045851, end_time:"2021-05-07T08:35:59.553832", exception:false.4, start_time:"2021-05-07T08:35:59.507981", status:"completed"}.4, tags:[]}.4, source:["We'll demonstrate the main methods in action by analyzing a [dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383) on the churn rate of telecom operator clients. Let's read the data (using `read_csv`),  and take a look at the first 5 lines using the `head` method:"]}, {"cell_type":"code".1, execution_count:2, id:"interesting-dodge", metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7", execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z", iopub.status.busy:"2021-05-07T08:35:59.645658Z", iopub.status.idle:"2021-05-07T08:35:59.731091Z", shell.execute_reply:"2021-05-07T08:35:59.731563Z"}, papermill:{"duration":0.13323, end_time:"2021-05-07T08:35:59.731738", exception:false.5, start_time:"2021-05-07T08:35:59.598508", status:"completed"}.5, tags:[]}.5, outputs:[{"data":{"text/html":["<div>\n", <style scoped>\n,     .dataframe tbody tr th:only-of-type {\n,         vertical-align: middle;\n,     }\n, \n.6,     .dataframe tbody tr th {\n, ...]
Index: []

[0 rows x 4452 columns]

In [ ]:
df.shape

(0, 4452)

In [ ]:
df.columns

Index(['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"',
       'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"',
       'papermill:{"duration":0.04692',
       'end_time:"2021-05-07T08:35:59.190175"', 'exception:false',
       'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}',
       'tags:[]}', 'source:["<center>\n"',
       ...
       'version:"2.3.2"}', 'kaggle:{"accelerator":"none"',
       'dataSources:[{"sourceType":"datasetVersion"', 'sourceId:205932}]',
       'isInternetEnabled:false', 'language:"python".1',
       'sourceType:"notebook"', 'isGpuEnabled:false}}', 'nbformat:4',
       'nbformat_minor:5}'],
      dtype='object', length=4452)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Columns: 4452 entries, {"cells":[{"cell_type":"markdown" to nbformat_minor:5}
dtypes: object(4452)
memory usage: 132.0+ bytes

In [ ]:
df.describe()

,"{""cells"":[{""cell_type"":""markdown""","id:""stretch-davis""","metadata:{""_uuid"":""1752ce061957fd1ce93d2e4db9494b7b29da7935""","papermill:{""duration"":0.04692","end_time:""2021-05-07T08:35:59.190175""",exception:false,"start_time:""2021-05-07T08:35:59.143255""","status:""completed""}",tags:[]},"source:[""<center>\n""",...,"version:""2.3.2""}","kaggle:{""accelerator"":""none""","dataSources:[{""sourceType"":""datasetVersion""",sourceId:205932}],isInternetEnabled:false,"language:""python"".1","sourceType:""notebook""",isGpuEnabled:false}},nbformat:4,nbformat_minor:5}
count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
unique,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

{"cells":[{"cell_type":"markdown"                               0
id:"stretch-davis"                                              0
metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"    0
papermill:{"duration":0.04692                                   0
end_time:"2021-05-07T08:35:59.190175"                           0
                                                               ..
language:"python".1                                             0
sourceType:"notebook"                                           0
isGpuEnabled:false}}                                            0
nbformat:4                                                      0
nbformat_minor:5}                                               0
Length: 4452, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Gender'].unique()

KeyError: 'Gender'

In [ ]:
df.dtypes

{"cells":[{"cell_type":"markdown"                               object
id:"stretch-davis"                                              object
metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"    object
papermill:{"duration":0.04692                                   object
end_time:"2021-05-07T08:35:59.190175"                           object
                                                                 ...
language:"python".1                                             object
sourceType:"notebook"                                           object
isGpuEnabled:false}}                                            object
nbformat:4                                                      object
nbformat_minor:5}                                               object
Length: 4452, dtype: object

In [ ]:
df.dtypes

{"cells":[{"cell_type":"markdown"                               object
id:"stretch-davis"                                              object
metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"    object
papermill:{"duration":0.04692                                   object
end_time:"2021-05-07T08:35:59.190175"                           object
                                                                 ...
language:"python".1                                             object
sourceType:"notebook"                                           object
isGpuEnabled:false}}                                            object
nbformat:4                                                      object
nbformat_minor:5}                                               object
Length: 4452, dtype: object

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '    \\n', '## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course \\n', '\\n', 'Author: [Yury Kashnitsky](https://yorko.github.io). Translated and edited by [Christina Butsko](https://www.linkedin.com/in/christinabutsko/), [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina), Sergey Isaev, and [Artem Trunov](https://www.linkedin.com/in/datamove/). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["# <center> Topic 1. Exploratory data analysis with Pandas\\n"', '\\n.1', '<img align=\\center\\" src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"  width=50% />\\n"', '\\n.2', '## Article outline\\n', '1. [Demonstration of main Pandas methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2. [First attempt at predicting telecom churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3. [Assignments](#3.-Assignments)\\n', '4. [Useful resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["## 1. Demonstration of main Pandas methods\\n"', 'Well... There are dozens of cool tutorials on Pandas and visual data analysis. If you are already familiar with these topics, you can wait for the 3rd article in the series, where we get into machine learning.  \\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)** is a Python library that provides extensive means for data analysis. Data scientists often work with data stored in table formats like `.csv`, `.tsv`, or `.xlsx`. Pandas makes it very convenient to load, process, and analyze such tabular data using SQL-like queries. In conjunction with `Matplotlib` and `Seaborn`, `Pandas` provides a wide range of opportunities for visual analysis of tabular data.\\n', '\\n.4', 'The main data structures in `Pandas` are implemented with **Series** and **DataFrame** classes. The former is a one-dimensional indexed array of some fixed data type. The latter is a two-dimensional data structure - a table - where each column contains data of the same type. You can see it as a dictionary of `Series` instances. `DataFrames` are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import numpy as np\\n"', 'import pandas as pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', ' 2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll demonstrate the main methods in action by analyzing a [dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383) on the churn rate of telecom operator clients. Let\'s read the data (using `read_csv`)', ' and take a look at the first 5 lines using the `head` method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style scoped>\\n', '    .dataframe tbody tr th:only-of-type {\\n', '        vertical-align: middle;\\n', '    }\\n', '\\n.6', '    .dataframe tbody tr th {\\n', '        vertical-align: top;\\n', '    }\\n.1', '\\n.7', '    .dataframe thead th {\\n', '        text-align: right;\\n', '    }\\n.2', '</style>\\n', '<table border=\\1\\" class=\\"dataframe\\">\\n"', '  <thead>\\n', '    <tr style=\\text-align: right;\\">\\n"', '      <th></th>\\n', '      <th>State</th>\\n', '      <th>Account length</th>\\n', '      <th>Area code</th>\\n', '      <th>International plan</th>\\n', '      <th>Voice mail plan</th>\\n', '      <th>Number vmail messages</th>\\n', '      <th>Total day minutes</th>\\n', '      <th>Total day calls</th>\\n', '      <th>Total day charge</th>\\n', '      <th>Total eve minutes</th>\\n', '      <th>Total eve calls</th>\\n', '      <th>Total eve charge</th>\\n', '      <th>Total night minutes</th>\\n', '      <th>Total night calls</th>\\n', '      <th>Total night charge</th>\\n', '      <th>Total intl minutes</th>\\n', '      <th>Total intl calls</th>\\n', '      <th>Total intl charge</th>\\n', '      <th>Customer service calls</th>\\n', '      <th>Churn</th>\\n', '    </tr>\\n', '  </thead>\\n', '  <tbody>\\n', '    <tr>\\n', '      <th>0</th>\\n', '      <td>KS</td>\\n', '      <td>128</td>\\n', '      <td>415</td>\\n', '      <td>No</td>\\n', '      <td>Yes</td>\\n', '      <td>25</td>\\n', '      <td>265.1</td>\\n', '      <td>110</td>\\n', '      <td>45.07</td>\\n', '      <td>197.4</td>\\n', '      <td>99</td>\\n', '      <td>16.78</td>\\n', '      <td>244.7</td>\\n', '      <td>91</td>\\n', '      <td>11.01</td>\\n', '      <td>10.0</td>\\n', '      <td>3</td>\\n', '      <td>2.70</td>\\n', '      <td>1</td>\\n', '      <td>False</td>\\n', '    </tr>\\n.1', '    <tr>\\n.1', '      <th>1</th>\\n', '      <td>OH</td>\\n', '      <td>107</td>\\n', '      <td>415</td>\\n.1', '      <td>No</td>\\n.1', '      <td>Yes</td>\\n.1', '      <td>26</td>\\n', '      <td>161.6</td>\\n', '      <td>123</td>\\n', '      <td>27.47</td>\\n', '      <td>195.5</td>\\n', '      <td>103</td>\\n', '      <td>16.62</td>\\n', '      <td>254.4</td>\\n', '      <td>103</td>\\n.1', '      <td>11.45</td>\\n', '      <td>13.7</td>\\n', '      <td>3</td>\\n.1', '      <td>3.70</td>\\n', '      <td>1</td>\\n.1', '      <td>False</td>\\n.1', '    </tr>\\n.2', '    <tr>\\n.2', '      <th>2</th>\\n', '      <td>NJ</td>\\n', '      <td>137</td>\\n', '      <td>415</td>\\n.2', '      <td>No</td>\\n.2', '      <td>No</td>\\n.3', '      <td>0</td>\\n', '      <td>243.4</td>\\n', '      <td>114</td>\\n', '      <td>41.38</td>\\n', '      <td>121.2</td>\\n', '      <td>110</td>\\n.1', '      <td>10.30</td>\\n', '      <td>162.6</td>\\n', '      <td>104</td>\\n', '      <td>7.32</td>\\n', '      <td>12.2</td>\\n', '      <td>5</td>\\n', '      <td>3.29</td>\\n', '      <td>0</td>\\n.1', '      <td>False</td>\\n.2', '    </tr>\\n.3', '    <tr>\\n.3', '      <th>3</th>\\n', '      <td>OH</td>\\n.1', '      <td>84</td>\\n', '      <td>408</td>\\n', '      <td>Yes</td>\\n.2', '      <td>No</td>\\n.4', '      <td>0</td>\\n.2', '      <td>299.4</td>\\n', '      <td>71</td>\\n', '      <td>50.90</td>\\n', '      <td>61.9</td>\\n', '      <td>88</td>\\n', '      <td>5.26</td>\\n', '      <td>196.9</td>\\n', '      <td>89</td>\\n', '      <td>8.86</td>\\n', '      <td>6.6</td>\\n', '      <td>7</td>\\n', '      <td>1.78</td>\\n', '      <td>2</td>\\n', '      <td>False</td>\\n.3', '    </tr>\\n.4', '    <tr>\\n.4', '      <th>4</th>\\n', '      <td>OK</td>\\n', '      <td>75</td>\\n', '      <td>415</td>\\n.3', '      <td>Yes</td>\\n.3', '      <td>No</td>\\n.5', '      <td>0</td>\\n.3', '      <td>166.7</td>\\n', '      <td>113</td>\\n', '      <td>28.34</td>\\n', '      <td>148.3</td>\\n', '      <td>122</td>\\n', '      <td>12.61</td>\\n', '      <td>186.9</td>\\n', '      <td>121</td>\\n', '      <td>8.41</td>\\n', '      <td>10.1</td>\\n', '      <td>3</td>\\n.2', '      <td>2.73</td>\\n', '      <td>3</td>\\n.3', '      <td>False</td>\\n.4', '    </tr>\\n.5', '  </tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["  State  Account length  Area code International plan Voice mail plan  \\\\\\n"', '0    KS             128        415                 No             Yes   \\n', '1    OH             107        415                 No             Yes   \\n', '2    NJ             137        415                 No              No   \\n', '3    OH              84        408                Yes              No   \\n', '4    OK              75        415                Yes              No   \\n', '\\n.8', '   Number vmail messages  Total day minutes  Total day calls  \\\\\\n', '0                     25              265.1              110   \\n', '1                     26              161.6              123   \\n', '2                      0              243.4              114   \\n', '3                      0              299.4               71   \\n', '4                      0              166.7              113   \\n', '\\n.9', '   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \\\\\\n', '0             45.07              197.4               99             16.78   \\n', '1             27.47              195.5              103             16.62   \\n', '2             41.38              121.2              110             10.30   \\n', '3             50.90               61.9               88              5.26   \\n', '4             28.34              148.3              122             12.61   \\n', '\\n.10', '   Total night minutes  Total night calls  Total night charge  \\\\\\n', '0                244.7                 91               11.01   \\n', '1                254.4                103               11.45   \\n', '2                162.6                104                7.32   \\n', '3                196.9                 89                8.86   \\n', '4                186.9                121                8.41   \\n', '\\n.11', '   Total intl minutes  Total intl calls  Total intl charge  \\\\\\n', '0                10.0                 3               2.70   \\n', '1                13.7                 3               3.70   \\n', '2                12.2                 5               3.29   \\n', '3                 6.6                 7               1.78   \\n', '4                10.1                 3               2.73   \\n', '\\n.12', '   Customer service calls  Churn  \\n', '0                       1  False  \\n', '1                       1  False  \\n', '2                       0  False  \\n', '3                       2  False  \\n', '4                       3  False  ]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df = pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About printing DataFrames in Jupyter notebooks</summary>\\n', '<p>\\n', 'In Jupyter notebooks, Pandas DataFrames are printed as these pretty tables seen above while `print(df.head())` is less nicely formatted.\\n', 'By default, Pandas displays 20 columns and 60 rows, so, if your DataFrame is bigger, use the `set_option` function as shown in the example below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns', 100)\\n", "pd.set_option('display.max_rows', 100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall that each row corresponds to one client, an **instance**, and columns are **features** of this instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s have a look at data dimensionality', ' feature names', ' and feature types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', ' 20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From the output', ' we can see that the table contains 3333 rows and 20 columns.\\n"', '\\n.15', "Now let's try printing out column names using `columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', " 'Account length'", " 'Area code'", " 'International plan'", '\\n"', "       'Voice mail plan', 'Number vmail messages', 'Total day minutes',\\n", "       'Total day calls', 'Total day charge', 'Total eve minutes',\\n", "       'Total eve calls', 'Total eve charge', 'Total night minutes',\\n", "       'Total night calls', 'Total night charge', 'Total intl minutes',\\n", "       'Total intl calls', 'Total intl charge', 'Customer service calls',\\n", "       'Churn'],\\n", "      dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We can use the `info()` method to output some general information about the dataframe: "]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class \'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex: 3333 entries, 0 to 3332\\n', 'Data columns (total 20 columns):\\n', ' #   Column                  Non-Null Count  Dtype  \\n', '---  ------                  --------------  -----  \\n', ' 0   State                   3333 non-null   object \\n', ' 1   Account length          3333 non-null   int64  \\n', ' 2   Area code               3333 non-null   int64  \\n', ' 3   International plan      3333 non-null   object \\n', ' 4   Voice mail plan         3333 non-null   object \\n', ' 5   Number vmail messages   3333 non-null   int64  \\n', ' 6   Total day minutes       3333 non-null   float64\\n', ' 7   Total day calls         3333 non-null   int64  \\n', ' 8   Total day charge        3333 non-null   float64\\n', ' 9   Total eve minutes       3333 non-null   float64\\n', ' 10  Total eve calls         3333 non-null   int64  \\n', ' 11  Total eve charge        3333 non-null   float64\\n', ' 12  Total night minutes     3333 non-null   float64\\n', ' 13  Total night calls       3333 non-null   int64  \\n', ' 14  Total night charge      3333 non-null   float64\\n', ' 15  Total intl minutes      3333 non-null   float64\\n', ' 16  Total intl calls        3333 non-null   int64  \\n', ' 17  Total intl charge       3333 non-null   float64\\n', ' 18  Customer service calls  3333 non-null   int64  \\n', ' 19  Churn                   3333 non-null   bool   \\n', 'dtypes: bool(1), float64(8), int64(8), object(3)\\n', 'memory usage: 498.1+ KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', ' `int64`', ' `float64` and `object` are the data types of our features. We see that one feature is logical (`bool`)', ' 3 features are of type `object`', ' and 16 features are numeric. With this same method', ' we can easily see if there are any missing values. Here', ' there are none because each column contains 3333 observations', ' the same number of rows we saw before with `shape`.\\n"', '\\n.16', "We can **change the column type** with the `astype` method. Let's apply this method to the `Churn` feature to convert it into `int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"] = df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '\\n', '## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course \\n', '\\n', 'Author: [Yury Kashnitsky](https://yorko.github.io). Translated and edited by [Christina Butsko](https://www.linkedin.com/in/christinabutsko/), [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina), Sergey Isaev, and [Artem Trunov](https://www.linkedin.com/in/datamove/). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["# <center> Topic 1. Exploratory data analysis with Pandas\\n"', '\\n.1', '<img align=\\center\\" src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"  width=50% />\\n"', '\\n.2', '## Article outline\\n', '1. [Demonstration of main Pandas methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2. [First attempt at predicting telecom churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3. [Assignments](#3.-Assignments)\\n', '4. [Useful resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["## 1. Demonstration of main Pandas methods\\n"', 'Well... There are dozens of cool tutorials on Pandas and visual data analysis. If you are already familiar with these topics, you can wait for the 3rd article in the series, where we get into machine learning.  \\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)** is a Python library that provides extensive means for data analysis. Data scientists often work with data stored in table formats like `.csv`, `.tsv`, or `.xlsx`. Pandas makes it very convenient to load, process, and analyze such tabular data using SQL-like queries. In conjunction with `Matplotlib` and `Seaborn`, `Pandas` provides a wide range of opportunities for visual analysis of tabular data.\\n', '\\n.4', 'The main data structures in `Pandas` are implemented with **Series** and **DataFrame** classes. The former is a one-dimensional indexed array of some fixed data type. The latter is a two-dimensional data structure - a table - where each column contains data of the same type. You can see it as a dictionary of `Series` instances. `DataFrames` are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import numpy as np\\n"', 'import pandas as pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', '2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll demonstrate the main methods in action by analyzing a [dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383) on the churn rate of telecom operator clients. Let\'s read the data (using `read_csv`)', 'and take a look at the first 5 lines using the `head` method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style scoped>\\n', '.dataframe tbody tr th:only-of-type {\\n', 'vertical-align: middle;\\n', '}\\n', '\\n.6', '.dataframe tbody tr th {\\n', 'vertical-align: top;\\n', '}\\n.1', '\\n.7', '.dataframe thead th {\\n', 'text-align: right;\\n', '}\\n.2', '</style>\\n', '<table border=\\1\\" class=\\"dataframe\\">\\n"', '<thead>\\n', '<tr style=\\text-align: right;\\">\\n"', '<th></th>\\n', '<th>State</th>\\n', '<th>Account length</th>\\n', '<th>Area code</th>\\n', '<th>International plan</th>\\n', '<th>Voice mail plan</th>\\n', '<th>Number vmail messages</th>\\n', '<th>Total day minutes</th>\\n', '<th>Total day calls</th>\\n', '<th>Total day charge</th>\\n', '<th>Total eve minutes</th>\\n', '<th>Total eve calls</th>\\n', '<th>Total eve charge</th>\\n', '<th>Total night minutes</th>\\n', '<th>Total night calls</th>\\n', '<th>Total night charge</th>\\n', '<th>Total intl minutes</th>\\n', '<th>Total intl calls</th>\\n', '<th>Total intl charge</th>\\n', '<th>Customer service calls</th>\\n', '<th>Churn</th>\\n', '</tr>\\n', '</thead>\\n', '<tbody>\\n', '<tr>\\n', '<th>0</th>\\n', '<td>KS</td>\\n', '<td>128</td>\\n', '<td>415</td>\\n', '<td>No</td>\\n', '<td>Yes</td>\\n', '<td>25</td>\\n', '<td>265.1</td>\\n', '<td>110</td>\\n', '<td>45.07</td>\\n', '<td>197.4</td>\\n', '<td>99</td>\\n', '<td>16.78</td>\\n', '<td>244.7</td>\\n', '<td>91</td>\\n', '<td>11.01</td>\\n', '<td>10.0</td>\\n', '<td>3</td>\\n', '<td>2.70</td>\\n', '<td>1</td>\\n', '<td>False</td>\\n', '</tr>\\n.1', '<tr>\\n.1', '<th>1</th>\\n', '<td>OH</td>\\n', '<td>107</td>\\n', '<td>415</td>\\n.1', '<td>No</td>\\n.1', '<td>Yes</td>\\n.1', '<td>26</td>\\n', '<td>161.6</td>\\n', '<td>123</td>\\n', '<td>27.47</td>\\n', '<td>195.5</td>\\n', '<td>103</td>\\n', '<td>16.62</td>\\n', '<td>254.4</td>\\n', '<td>103</td>\\n.1', '<td>11.45</td>\\n', '<td>13.7</td>\\n', '<td>3</td>\\n.1', '<td>3.70</td>\\n', '<td>1</td>\\n.1', '<td>False</td>\\n.1', '</tr>\\n.2', '<tr>\\n.2', '<th>2</th>\\n', '<td>NJ</td>\\n', '<td>137</td>\\n', '<td>415</td>\\n.2', '<td>No</td>\\n.2', '<td>No</td>\\n.3', '<td>0</td>\\n', '<td>243.4</td>\\n', '<td>114</td>\\n', '<td>41.38</td>\\n', '<td>121.2</td>\\n', '<td>110</td>\\n.1', '<td>10.30</td>\\n', '<td>162.6</td>\\n', '<td>104</td>\\n', '<td>7.32</td>\\n', '<td>12.2</td>\\n', '<td>5</td>\\n', '<td>3.29</td>\\n', '<td>0</td>\\n.1', '<td>False</td>\\n.2', '</tr>\\n.3', '<tr>\\n.3', '<th>3</th>\\n', '<td>OH</td>\\n.1', '<td>84</td>\\n', '<td>408</td>\\n', '<td>Yes</td>\\n.2', '<td>No</td>\\n.4', '<td>0</td>\\n.2', '<td>299.4</td>\\n', '<td>71</td>\\n', '<td>50.90</td>\\n', '<td>61.9</td>\\n', '<td>88</td>\\n', '<td>5.26</td>\\n', '<td>196.9</td>\\n', '<td>89</td>\\n', '<td>8.86</td>\\n', '<td>6.6</td>\\n', '<td>7</td>\\n', '<td>1.78</td>\\n', '<td>2</td>\\n', '<td>False</td>\\n.3', '</tr>\\n.4', '<tr>\\n.4', '<th>4</th>\\n', '<td>OK</td>\\n', '<td>75</td>\\n', '<td>415</td>\\n.3', '<td>Yes</td>\\n.3', '<td>No</td>\\n.5', '<td>0</td>\\n.3', '<td>166.7</td>\\n', '<td>113</td>\\n', '<td>28.34</td>\\n', '<td>148.3</td>\\n', '<td>122</td>\\n', '<td>12.61</td>\\n', '<td>186.9</td>\\n', '<td>121</td>\\n', '<td>8.41</td>\\n', '<td>10.1</td>\\n', '<td>3</td>\\n.2', '<td>2.73</td>\\n', '<td>3</td>\\n.3', '<td>False</td>\\n.4', '</tr>\\n.5', '</tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["  State  Account length  Area code International plan Voice mail plan  \\\\\\n"', '0    KS             128        415                 No             Yes   \\n', '1    OH             107        415                 No             Yes   \\n', '2    NJ             137        415                 No              No   \\n', '3    OH              84        408                Yes              No   \\n', '4    OK              75        415                Yes              No   \\n', '\\n.8', 'Number vmail messages  Total day minutes  Total day calls  \\\\\\n', '0                     25              265.1              110   \\n', '1                     26              161.6              123   \\n', '2                      0              243.4              114   \\n', '3                      0              299.4               71   \\n', '4                      0              166.7              113   \\n', '\\n.9', 'Total day charge  Total eve minutes  Total eve calls  Total eve charge  \\\\\\n', '0             45.07              197.4               99             16.78   \\n', '1             27.47              195.5              103             16.62   \\n', '2             41.38              121.2              110             10.30   \\n', '3             50.90               61.9               88              5.26   \\n', '4             28.34              148.3              122             12.61   \\n', '\\n.10', 'Total night minutes  Total night calls  Total night charge  \\\\\\n', '0                244.7                 91               11.01   \\n', '1                254.4                103               11.45   \\n', '2                162.6                104                7.32   \\n', '3                196.9                 89                8.86   \\n', '4                186.9                121                8.41   \\n', '\\n.11', 'Total intl minutes  Total intl calls  Total intl charge  \\\\\\n', '0                10.0                 3               2.70   \\n', '1                13.7                 3               3.70   \\n', '2                12.2                 5               3.29   \\n', '3                 6.6                 7               1.78   \\n', '4                10.1                 3               2.73   \\n', '\\n.12', 'Customer service calls  Churn  \\n', '0                       1  False  \\n', '1                       1  False  \\n', '2                       0  False  \\n', '3                       2  False  \\n', '4                       3  False  ]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df = pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About printing DataFrames in Jupyter notebooks</summary>\\n', '<p>\\n', 'In Jupyter notebooks, Pandas DataFrames are printed as these pretty tables seen above while `print(df.head())` is less nicely formatted.\\n', 'By default, Pandas displays 20 columns and 60 rows, so, if your DataFrame is bigger, use the `set_option` function as shown in the example below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns', 100)\\n", "pd.set_option('display.max_rows', 100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall that each row corresponds to one client, an **instance**, and columns are **features** of this instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s have a look at data dimensionality', 'feature names', 'and feature types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', '20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From the output', 'we can see that the table contains 3333 rows and 20 columns.\\n"', '\\n.15', "Now let's try printing out column names using `columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', "'Account length'", "'Area code'", "'International plan'", '\\n"', "'Voice mail plan', 'Number vmail messages', 'Total day minutes',\\n", "'Total day calls', 'Total day charge', 'Total eve minutes',\\n", "'Total eve calls', 'Total eve charge', 'Total night minutes',\\n", "'Total night calls', 'Total night charge', 'Total intl minutes',\\n", "'Total intl calls', 'Total intl charge', 'Customer service calls',\\n", "'Churn'],\\n", "dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We can use the `info()` method to output some general information about the dataframe: "]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class \'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex: 3333 entries, 0 to 3332\\n', 'Data columns (total 20 columns):\\n', '#   Column                  Non-Null Count  Dtype  \\n', '---  ------                  --------------  -----  \\n', '0   State                   3333 non-null   object \\n', '1   Account length          3333 non-null   int64  \\n', '2   Area code               3333 non-null   int64  \\n', '3   International plan      3333 non-null   object \\n', '4   Voice mail plan         3333 non-null   object \\n', '5   Number vmail messages   3333 non-null   int64  \\n', '6   Total day minutes       3333 non-null   float64\\n', '7   Total day calls         3333 non-null   int64  \\n', '8   Total day charge        3333 non-null   float64\\n', '9   Total eve minutes       3333 non-null   float64\\n', '10  Total eve calls         3333 non-null   int64  \\n', '11  Total eve charge        3333 non-null   float64\\n', '12  Total night minutes     3333 non-null   float64\\n', '13  Total night calls       3333 non-null   int64  \\n', '14  Total night charge      3333 non-null   float64\\n', '15  Total intl minutes      3333 non-null   float64\\n', '16  Total intl calls        3333 non-null   int64  \\n', '17  Total intl charge       3333 non-null   float64\\n', '18  Customer service calls  3333 non-null   int64  \\n', '19  Churn                   3333 non-null   bool   \\n', 'dtypes: bool(1), float64(8), int64(8), object(3)\\n', 'memory usage: 498.1+ KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', '`int64`', '`float64` and `object` are the data types of our features. We see that one feature is logical (`bool`)', '3 features are of type `object`', 'and 16 features are numeric. With this same method', 'we can easily see if there are any missing values. Here', 'there are none because each column contains 3333 observations', 'the same number of rows we saw before with `shape`.\\n"', '\\n.16', "We can **change the column type** with the `astype` method. Let's apply this method to the `Churn` feature to convert it into `int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"] = df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:"2021-05-07T08:36:00.714887"', 'exception:false.15', 'start_time:"2021-05-07T08:36:00.669434"', 'status:"completed"}.15', 'tags:[]}.15', 'source:["The `describe` method shows basic statistical characteristics of each numerical feature (`int64` and `float64` types): number of non-missing values', 'mean', 'standard deviation', 'range', 'median', '0.25 and 0.75 quartiles."]}', '{"cell_type":"code".6', 'execution_count:7', 'id:"improving-spencer"', 'metadata:{"_uuid":"24e1d394f938980403a736421b4cf855ddb8ef8c"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.813975Z"', 'iopub.status.busy:"2021-05-07T08:36:00.813039Z"', 'iopub.status.idle:"2021-05-07T08:36:00.874306Z"', 'shell.execute_reply:"2021-05-07T08:36:00.874785Z"}', 'papermill:{"duration":0.113807', 'end_time:"2021-05-07T08:36:00.874959"', 'exception:false.16', 'start_time:"2021-05-07T08:36:00.761152"', 'status:"completed"}.16', 'tags:[]}.16', 'outputs:[{"data":{"text/html":["<div>\\n".1', '

In [ ]:
df.columns = df.columns.str.strip()      # remove spaces
df.columns = df.columns.str.replace(' ', '_')  # replace spaces with underscores

In [ ]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

KeyError: 'TotalCharges'

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img_src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '\\n', '##_[mlcourse.ai](https://mlcourse.ai)_–_Open_Machine_Learning_Course_\\n', '\\n', 'Author:_[Yury_Kashnitsky](https://yorko.github.io)._Translated_and_edited_by_[Christina_Butsko](https://www.linkedin.com/in/christinabutsko/),_[Yuanyuan_Pao](https://www.linkedin.com/in/yuanyuanpao/),_[Anastasia_Manokhina](https://www.linkedin.com/in/anastasiamanokhina),_Sergey_Isaev,_and_[Artem_Trunov](https://www.linkedin.com/in/datamove/)._This_material_is_subject_to_the_terms_and_conditions_of_the_[Creative_Commons_CC_BY-NC-SA_4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)_license._Free_use_is_permitted_for_any_non-commercial_purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["#_<center>_Topic_1._Exploratory_data_analysis_with_Pandas\\n"', '\\n.1', '<img_align=\\center\\"_src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"__width=50%_/>\\n"', '\\n.2', '##_Article_outline\\n', '1._[Demonstration_of_main_Pandas_methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2._[First_attempt_at_predicting_telecom_churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3._[Assignments](#3.-Assignments)\\n', '4._[Useful_resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["##_1._Demonstration_of_main_Pandas_methods\\n"', 'Well..._There_are_dozens_of_cool_tutorials_on_Pandas_and_visual_data_analysis._If_you_are_already_familiar_with_these_topics,_you_can_wait_for_the_3rd_article_in_the_series,_where_we_get_into_machine_learning.__\\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)**_is_a_Python_library_that_provides_extensive_means_for_data_analysis._Data_scientists_often_work_with_data_stored_in_table_formats_like_`.csv`,_`.tsv`,_or_`.xlsx`._Pandas_makes_it_very_convenient_to_load,_process,_and_analyze_such_tabular_data_using_SQL-like_queries._In_conjunction_with_`Matplotlib`_and_`Seaborn`,_`Pandas`_provides_a_wide_range_of_opportunities_for_visual_analysis_of_tabular_data.\\n', '\\n.4', 'The_main_data_structures_in_`Pandas`_are_implemented_with_**Series**_and_**DataFrame**_classes._The_former_is_a_one-dimensional_indexed_array_of_some_fixed_data_type._The_latter_is_a_two-dimensional_data_structure_-_a_table_-_where_each_column_contains_data_of_the_same_type._You_can_see_it_as_a_dictionary_of_`Series`_instances._`DataFrames`_are_great_for_representing_real_data:_rows_correspond_to_instances_(examples,_observations,_etc.),_and_columns_correspond_to_features_of_these_instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import_numpy_as_np\\n"', 'import_pandas_as_pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', '2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll_demonstrate_the_main_methods_in_action_by_analyzing_a_[dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383)_on_the_churn_rate_of_telecom_operator_clients._Let\'s_read_the_data_(using_`read_csv`)', 'and_take_a_look_at_the_first_5_lines_using_the_`head`_method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style_scoped>\\n', '.dataframe_tbody_tr_th:only-of-type_{\\n', 'vertical-align:_middle;\\n', '}\\n', '\\n.6', '.dataframe_tbody_tr_th_{\\n', 'vertical-align:_top;\\n', '}\\n.1', '\\n.7', '.dataframe_thead_th_{\\n', 'text-align:_right;\\n', '}\\n.2', '</style>\\n', '<table_border=\\1\\"_class=\\"dataframe\\">\\n"', '<thead>\\n', '<tr_style=\\text-align:_right;\\">\\n"', '<th></th>\\n', '<th>State</th>\\n', '<th>Account_length</th>\\n', '<th>Area_code</th>\\n', '<th>International_plan</th>\\n', '<th>Voice_mail_plan</th>\\n', '<th>Number_vmail_messages</th>\\n', '<th>Total_day_minutes</th>\\n', '<th>Total_day_calls</th>\\n', '<th>Total_day_charge</th>\\n', '<th>Total_eve_minutes</th>\\n', '<th>Total_eve_calls</th>\\n', '<th>Total_eve_charge</th>\\n', '<th>Total_night_minutes</th>\\n', '<th>Total_night_calls</th>\\n', '<th>Total_night_charge</th>\\n', '<th>Total_intl_minutes</th>\\n', '<th>Total_intl_calls</th>\\n', '<th>Total_intl_charge</th>\\n', '<th>Customer_service_calls</th>\\n', '<th>Churn</th>\\n', '</tr>\\n', '</thead>\\n', '<tbody>\\n', '<tr>\\n', '<th>0</th>\\n', '<td>KS</td>\\n', '<td>128</td>\\n', '<td>415</td>\\n', '<td>No</td>\\n', '<td>Yes</td>\\n', '<td>25</td>\\n', '<td>265.1</td>\\n', '<td>110</td>\\n', '<td>45.07</td>\\n', '<td>197.4</td>\\n', '<td>99</td>\\n', '<td>16.78</td>\\n', '<td>244.7</td>\\n', '<td>91</td>\\n', '<td>11.01</td>\\n', '<td>10.0</td>\\n', '<td>3</td>\\n', '<td>2.70</td>\\n', '<td>1</td>\\n', '<td>False</td>\\n', '</tr>\\n.1', '<tr>\\n.1', '<th>1</th>\\n', '<td>OH</td>\\n', '<td>107</td>\\n', '<td>415</td>\\n.1', '<td>No</td>\\n.1', '<td>Yes</td>\\n.1', '<td>26</td>\\n', '<td>161.6</td>\\n', '<td>123</td>\\n', '<td>27.47</td>\\n', '<td>195.5</td>\\n', '<td>103</td>\\n', '<td>16.62</td>\\n', '<td>254.4</td>\\n', '<td>103</td>\\n.1', '<td>11.45</td>\\n', '<td>13.7</td>\\n', '<td>3</td>\\n.1', '<td>3.70</td>\\n', '<td>1</td>\\n.1', '<td>False</td>\\n.1', '</tr>\\n.2', '<tr>\\n.2', '<th>2</th>\\n', '<td>NJ</td>\\n', '<td>137</td>\\n', '<td>415</td>\\n.2', '<td>No</td>\\n.2', '<td>No</td>\\n.3', '<td>0</td>\\n', '<td>243.4</td>\\n', '<td>114</td>\\n', '<td>41.38</td>\\n', '<td>121.2</td>\\n', '<td>110</td>\\n.1', '<td>10.30</td>\\n', '<td>162.6</td>\\n', '<td>104</td>\\n', '<td>7.32</td>\\n', '<td>12.2</td>\\n', '<td>5</td>\\n', '<td>3.29</td>\\n', '<td>0</td>\\n.1', '<td>False</td>\\n.2', '</tr>\\n.3', '<tr>\\n.3', '<th>3</th>\\n', '<td>OH</td>\\n.1', '<td>84</td>\\n', '<td>408</td>\\n', '<td>Yes</td>\\n.2', '<td>No</td>\\n.4', '<td>0</td>\\n.2', '<td>299.4</td>\\n', '<td>71</td>\\n', '<td>50.90</td>\\n', '<td>61.9</td>\\n', '<td>88</td>\\n', '<td>5.26</td>\\n', '<td>196.9</td>\\n', '<td>89</td>\\n', '<td>8.86</td>\\n', '<td>6.6</td>\\n', '<td>7</td>\\n', '<td>1.78</td>\\n', '<td>2</td>\\n', '<td>False</td>\\n.3', '</tr>\\n.4', '<tr>\\n.4', '<th>4</th>\\n', '<td>OK</td>\\n', '<td>75</td>\\n', '<td>415</td>\\n.3', '<td>Yes</td>\\n.3', '<td>No</td>\\n.5', '<td>0</td>\\n.3', '<td>166.7</td>\\n', '<td>113</td>\\n', '<td>28.34</td>\\n', '<td>148.3</td>\\n', '<td>122</td>\\n', '<td>12.61</td>\\n', '<td>186.9</td>\\n', '<td>121</td>\\n', '<td>8.41</td>\\n', '<td>10.1</td>\\n', '<td>3</td>\\n.2', '<td>2.73</td>\\n', '<td>3</td>\\n.3', '<td>False</td>\\n.4', '</tr>\\n.5', '</tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["__State__Account_length__Area_code_International_plan_Voice_mail_plan__\\\\\\n"', '0____KS_____________128________415_________________No_____________Yes___\\n', '1____OH_____________107________415_________________No_____________Yes___\\n', '2____NJ_____________137________415_________________No______________No___\\n', '3____OH______________84________408________________Yes______________No___\\n', '4____OK______________75________415________________Yes______________No___\\n', '\\n.8', 'Number_vmail_messages__Total_day_minutes__Total_day_calls__\\\\\\n', '0_____________________25______________265.1______________110___\\n', '1_____________________26______________161.6______________123___\\n', '2______________________0______________243.4______________114___\\n', '3______________________0______________299.4_______________71___\\n', '4______________________0______________166.7______________113___\\n', '\\n.9', 'Total_day_charge__Total_eve_minutes__Total_eve_calls__Total_eve_charge__\\\\\\n', '0_____________45.07______________197.4_______________99_____________16.78___\\n', '1_____________27.47______________195.5______________103_____________16.62___\\n', '2_____________41.38______________121.2______________110_____________10.30___\\n', '3_____________50.90_______________61.9_______________88______________5.26___\\n', '4_____________28.34______________148.3______________122_____________12.61___\\n', '\\n.10', 'Total_night_minutes__Total_night_calls__Total_night_charge__\\\\\\n', '0________________244.7_________________91_______________11.01___\\n', '1________________254.4________________103_______________11.45___\\n', '2________________162.6________________104________________7.32___\\n', '3________________196.9_________________89________________8.86___\\n', '4________________186.9________________121________________8.41___\\n', '\\n.11', 'Total_intl_minutes__Total_intl_calls__Total_intl_charge__\\\\\\n', '0________________10.0_________________3_______________2.70___\\n', '1________________13.7_________________3_______________3.70___\\n', '2________________12.2_________________5_______________3.29___\\n', '3_________________6.6_________________7_______________1.78___\\n', '4________________10.1_________________3_______________2.73___\\n', '\\n.12', 'Customer_service_calls__Churn__\\n', '0_______________________1__False__\\n', '1_______________________1__False__\\n', '2_______________________0__False__\\n', '3_______________________2__False__\\n', '4_______________________3__False__]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df_=_pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About_printing_DataFrames_in_Jupyter_notebooks</summary>\\n', '<p>\\n', 'In_Jupyter_notebooks,_Pandas_DataFrames_are_printed_as_these_pretty_tables_seen_above_while_`print(df.head())`_is_less_nicely_formatted.\\n', 'By_default,_Pandas_displays_20_columns_and_60_rows,_so,_if_your_DataFrame_is_bigger,_use_the_`set_option`_function_as_shown_in_the_example_below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns',_100)\\n", "pd.set_option('display.max_rows',_100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall_that_each_row_corresponds_to_one_client,_an_**instance**,_and_columns_are_**features**_of_this_instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s_have_a_look_at_data_dimensionality', 'feature_names', 'and_feature_types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', '20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From_the_output', 'we_can_see_that_the_table_contains_3333_rows_and_20_columns.\\n"', '\\n.15', "Now_let's_try_printing_out_column_names_using_`columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', "'Account_length'", "'Area_code'", "'International_plan'", '\\n"', "'Voice_mail_plan',_'Number_vmail_messages',_'Total_day_minutes',\\n", "'Total_day_calls',_'Total_day_charge',_'Total_eve_minutes',\\n", "'Total_eve_calls',_'Total_eve_charge',_'Total_night_minutes',\\n", "'Total_night_calls',_'Total_night_charge',_'Total_intl_minutes',\\n", "'Total_intl_calls',_'Total_intl_charge',_'Customer_service_calls',\\n", "'Churn'],\\n", "dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We_can_use_the_`info()`_method_to_output_some_general_information_about_the_dataframe:_"]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class_\'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex:_3333_entries,_0_to_3332\\n', 'Data_columns_(total_20_columns):\\n', '#___Column__________________Non-Null_Count__Dtype__\\n', '---__------__________________--------------__-----__\\n', '0___State___________________3333_non-null___object_\\n', '1___Account_length__________3333_non-null___int64__\\n', '2___Area_code_______________3333_non-null___int64__\\n', '3___International_plan______3333_non-null___object_\\n', '4___Voice_mail_plan_________3333_non-null___object_\\n', '5___Number_vmail_messages___3333_non-null___int64__\\n', '6___Total_day_minutes_______3333_non-null___float64\\n', '7___Total_day_calls_________3333_non-null___int64__\\n', '8___Total_day_charge________3333_non-null___float64\\n', '9___Total_eve_minutes_______3333_non-null___float64\\n', '10__Total_eve_calls_________3333_non-null___int64__\\n', '11__Total_eve_charge________3333_non-null___float64\\n', '12__Total_night_minutes_____3333_non-null___float64\\n', '13__Total_night_calls_______3333_non-null___int64__\\n', '14__Total_night_charge______3333_non-null___float64\\n', '15__Total_intl_minutes______3333_non-null___float64\\n', '16__Total_intl_calls________3333_non-null___int64__\\n', '17__Total_intl_charge_______3333_non-null___float64\\n', '18__Customer_service_calls__3333_non-null___int64__\\n', '19__Churn___________________3333_non-null___bool___\\n', 'dtypes:_bool(1),_float64(8),_int64(8),_object(3)\\n', 'memory_usage:_498.1+_KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', '`int64`', '`float64`_and_`object`_are_the_data_types_of_our_features._We_see_that_one_feature_is_logical_(`bool`)', '3_features_are_of_type_`object`', 'and_16_features_are_numeric._With_this_same_method', 'we_can_easily_see_if_there_are_any_missing_values._Here', 'there_are_none_because_each_column_contains_3333_observations', 'the_same_number_of_rows_we_saw_before_with_`shape`.\\n"', '\\n.16', "We_can_**change_the_column_type**_with_the_`astype`_method._Let's_apply_this_method_to_the_`Churn`_feature_to_convert_it_into_`int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"]_=_df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:"2021-05-07T08:36:00.714887"', 'exception:false.15', 'start_time:"2021-05-07T08:36:00.669434"', 'status:"completed"}.15', 'tags:[]}.15', 'source:["The_`describe`_method_shows_basic_statistical_characteristics_of_each_numerical_feature_(`int64`_and_`float64`_types):_number_of_non-missing_values', 'mean', 'standard_deviation', 'range', 'median', '0.25_and_0.75_quartiles."]}', '{"cell_type":"code".6', 'execution_count:7', 'id:"improving-spencer"', 'metadata:{"_uuid":"24e1d394f938980403a736421b4cf855ddb8ef8c"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.813975Z"', 'iopub.status.busy:"2021-05-07T08:36:00.813039Z"', 'iopub.status.idle:"2021-05-07T08:36:00.874306Z"', 'shell.execute_reply:"2021-05-07T08:36:00.874785Z"}', 'papermill:{"duration":0.113807', 'end_time:"2021-05-07T08:36:00.874959"', 'exception:false.16', 'start_time:"2021-05-07T08:36:00.761152"', 'status:"completed"}.16', 'tags:[]}.16', 'outputs:[{"data":{"text/html":["<div>\\n".1', '

In [ ]:
df.columns = df.columns.str.strip()   # remove leading/trailing spaces

In [ ]:
df.columns = df.columns.str.replace(' ', '_')  # replace spaces with underscores

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img_src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '\\n', '##_[mlcourse.ai](https://mlcourse.ai)_–_Open_Machine_Learning_Course_\\n', '\\n', 'Author:_[Yury_Kashnitsky](https://yorko.github.io)._Translated_and_edited_by_[Christina_Butsko](https://www.linkedin.com/in/christinabutsko/),_[Yuanyuan_Pao](https://www.linkedin.com/in/yuanyuanpao/),_[Anastasia_Manokhina](https://www.linkedin.com/in/anastasiamanokhina),_Sergey_Isaev,_and_[Artem_Trunov](https://www.linkedin.com/in/datamove/)._This_material_is_subject_to_the_terms_and_conditions_of_the_[Creative_Commons_CC_BY-NC-SA_4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)_license._Free_use_is_permitted_for_any_non-commercial_purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["#_<center>_Topic_1._Exploratory_data_analysis_with_Pandas\\n"', '\\n.1', '<img_align=\\center\\"_src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"__width=50%_/>\\n"', '\\n.2', '##_Article_outline\\n', '1._[Demonstration_of_main_Pandas_methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2._[First_attempt_at_predicting_telecom_churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3._[Assignments](#3.-Assignments)\\n', '4._[Useful_resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["##_1._Demonstration_of_main_Pandas_methods\\n"', 'Well..._There_are_dozens_of_cool_tutorials_on_Pandas_and_visual_data_analysis._If_you_are_already_familiar_with_these_topics,_you_can_wait_for_the_3rd_article_in_the_series,_where_we_get_into_machine_learning.__\\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)**_is_a_Python_library_that_provides_extensive_means_for_data_analysis._Data_scientists_often_work_with_data_stored_in_table_formats_like_`.csv`,_`.tsv`,_or_`.xlsx`._Pandas_makes_it_very_convenient_to_load,_process,_and_analyze_such_tabular_data_using_SQL-like_queries._In_conjunction_with_`Matplotlib`_and_`Seaborn`,_`Pandas`_provides_a_wide_range_of_opportunities_for_visual_analysis_of_tabular_data.\\n', '\\n.4', 'The_main_data_structures_in_`Pandas`_are_implemented_with_**Series**_and_**DataFrame**_classes._The_former_is_a_one-dimensional_indexed_array_of_some_fixed_data_type._The_latter_is_a_two-dimensional_data_structure_-_a_table_-_where_each_column_contains_data_of_the_same_type._You_can_see_it_as_a_dictionary_of_`Series`_instances._`DataFrames`_are_great_for_representing_real_data:_rows_correspond_to_instances_(examples,_observations,_etc.),_and_columns_correspond_to_features_of_these_instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import_numpy_as_np\\n"', 'import_pandas_as_pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', '2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll_demonstrate_the_main_methods_in_action_by_analyzing_a_[dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383)_on_the_churn_rate_of_telecom_operator_clients._Let\'s_read_the_data_(using_`read_csv`)', 'and_take_a_look_at_the_first_5_lines_using_the_`head`_method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style_scoped>\\n', '.dataframe_tbody_tr_th:only-of-type_{\\n', 'vertical-align:_middle;\\n', '}\\n', '\\n.6', '.dataframe_tbody_tr_th_{\\n', 'vertical-align:_top;\\n', '}\\n.1', '\\n.7', '.dataframe_thead_th_{\\n', 'text-align:_right;\\n', '}\\n.2', '</style>\\n', '<table_border=\\1\\"_class=\\"dataframe\\">\\n"', '<thead>\\n', '<tr_style=\\text-align:_right;\\">\\n"', '<th></th>\\n', '<th>State</th>\\n', '<th>Account_length</th>\\n', '<th>Area_code</th>\\n', '<th>International_plan</th>\\n', '<th>Voice_mail_plan</th>\\n', '<th>Number_vmail_messages</th>\\n', '<th>Total_day_minutes</th>\\n', '<th>Total_day_calls</th>\\n', '<th>Total_day_charge</th>\\n', '<th>Total_eve_minutes</th>\\n', '<th>Total_eve_calls</th>\\n', '<th>Total_eve_charge</th>\\n', '<th>Total_night_minutes</th>\\n', '<th>Total_night_calls</th>\\n', '<th>Total_night_charge</th>\\n', '<th>Total_intl_minutes</th>\\n', '<th>Total_intl_calls</th>\\n', '<th>Total_intl_charge</th>\\n', '<th>Customer_service_calls</th>\\n', '<th>Churn</th>\\n', '</tr>\\n', '</thead>\\n', '<tbody>\\n', '<tr>\\n', '<th>0</th>\\n', '<td>KS</td>\\n', '<td>128</td>\\n', '<td>415</td>\\n', '<td>No</td>\\n', '<td>Yes</td>\\n', '<td>25</td>\\n', '<td>265.1</td>\\n', '<td>110</td>\\n', '<td>45.07</td>\\n', '<td>197.4</td>\\n', '<td>99</td>\\n', '<td>16.78</td>\\n', '<td>244.7</td>\\n', '<td>91</td>\\n', '<td>11.01</td>\\n', '<td>10.0</td>\\n', '<td>3</td>\\n', '<td>2.70</td>\\n', '<td>1</td>\\n', '<td>False</td>\\n', '</tr>\\n.1', '<tr>\\n.1', '<th>1</th>\\n', '<td>OH</td>\\n', '<td>107</td>\\n', '<td>415</td>\\n.1', '<td>No</td>\\n.1', '<td>Yes</td>\\n.1', '<td>26</td>\\n', '<td>161.6</td>\\n', '<td>123</td>\\n', '<td>27.47</td>\\n', '<td>195.5</td>\\n', '<td>103</td>\\n', '<td>16.62</td>\\n', '<td>254.4</td>\\n', '<td>103</td>\\n.1', '<td>11.45</td>\\n', '<td>13.7</td>\\n', '<td>3</td>\\n.1', '<td>3.70</td>\\n', '<td>1</td>\\n.1', '<td>False</td>\\n.1', '</tr>\\n.2', '<tr>\\n.2', '<th>2</th>\\n', '<td>NJ</td>\\n', '<td>137</td>\\n', '<td>415</td>\\n.2', '<td>No</td>\\n.2', '<td>No</td>\\n.3', '<td>0</td>\\n', '<td>243.4</td>\\n', '<td>114</td>\\n', '<td>41.38</td>\\n', '<td>121.2</td>\\n', '<td>110</td>\\n.1', '<td>10.30</td>\\n', '<td>162.6</td>\\n', '<td>104</td>\\n', '<td>7.32</td>\\n', '<td>12.2</td>\\n', '<td>5</td>\\n', '<td>3.29</td>\\n', '<td>0</td>\\n.1', '<td>False</td>\\n.2', '</tr>\\n.3', '<tr>\\n.3', '<th>3</th>\\n', '<td>OH</td>\\n.1', '<td>84</td>\\n', '<td>408</td>\\n', '<td>Yes</td>\\n.2', '<td>No</td>\\n.4', '<td>0</td>\\n.2', '<td>299.4</td>\\n', '<td>71</td>\\n', '<td>50.90</td>\\n', '<td>61.9</td>\\n', '<td>88</td>\\n', '<td>5.26</td>\\n', '<td>196.9</td>\\n', '<td>89</td>\\n', '<td>8.86</td>\\n', '<td>6.6</td>\\n', '<td>7</td>\\n', '<td>1.78</td>\\n', '<td>2</td>\\n', '<td>False</td>\\n.3', '</tr>\\n.4', '<tr>\\n.4', '<th>4</th>\\n', '<td>OK</td>\\n', '<td>75</td>\\n', '<td>415</td>\\n.3', '<td>Yes</td>\\n.3', '<td>No</td>\\n.5', '<td>0</td>\\n.3', '<td>166.7</td>\\n', '<td>113</td>\\n', '<td>28.34</td>\\n', '<td>148.3</td>\\n', '<td>122</td>\\n', '<td>12.61</td>\\n', '<td>186.9</td>\\n', '<td>121</td>\\n', '<td>8.41</td>\\n', '<td>10.1</td>\\n', '<td>3</td>\\n.2', '<td>2.73</td>\\n', '<td>3</td>\\n.3', '<td>False</td>\\n.4', '</tr>\\n.5', '</tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["__State__Account_length__Area_code_International_plan_Voice_mail_plan__\\\\\\n"', '0____KS_____________128________415_________________No_____________Yes___\\n', '1____OH_____________107________415_________________No_____________Yes___\\n', '2____NJ_____________137________415_________________No______________No___\\n', '3____OH______________84________408________________Yes______________No___\\n', '4____OK______________75________415________________Yes______________No___\\n', '\\n.8', 'Number_vmail_messages__Total_day_minutes__Total_day_calls__\\\\\\n', '0_____________________25______________265.1______________110___\\n', '1_____________________26______________161.6______________123___\\n', '2______________________0______________243.4______________114___\\n', '3______________________0______________299.4_______________71___\\n', '4______________________0______________166.7______________113___\\n', '\\n.9', 'Total_day_charge__Total_eve_minutes__Total_eve_calls__Total_eve_charge__\\\\\\n', '0_____________45.07______________197.4_______________99_____________16.78___\\n', '1_____________27.47______________195.5______________103_____________16.62___\\n', '2_____________41.38______________121.2______________110_____________10.30___\\n', '3_____________50.90_______________61.9_______________88______________5.26___\\n', '4_____________28.34______________148.3______________122_____________12.61___\\n', '\\n.10', 'Total_night_minutes__Total_night_calls__Total_night_charge__\\\\\\n', '0________________244.7_________________91_______________11.01___\\n', '1________________254.4________________103_______________11.45___\\n', '2________________162.6________________104________________7.32___\\n', '3________________196.9_________________89________________8.86___\\n', '4________________186.9________________121________________8.41___\\n', '\\n.11', 'Total_intl_minutes__Total_intl_calls__Total_intl_charge__\\\\\\n', '0________________10.0_________________3_______________2.70___\\n', '1________________13.7_________________3_______________3.70___\\n', '2________________12.2_________________5_______________3.29___\\n', '3_________________6.6_________________7_______________1.78___\\n', '4________________10.1_________________3_______________2.73___\\n', '\\n.12', 'Customer_service_calls__Churn__\\n', '0_______________________1__False__\\n', '1_______________________1__False__\\n', '2_______________________0__False__\\n', '3_______________________2__False__\\n', '4_______________________3__False__]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df_=_pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About_printing_DataFrames_in_Jupyter_notebooks</summary>\\n', '<p>\\n', 'In_Jupyter_notebooks,_Pandas_DataFrames_are_printed_as_these_pretty_tables_seen_above_while_`print(df.head())`_is_less_nicely_formatted.\\n', 'By_default,_Pandas_displays_20_columns_and_60_rows,_so,_if_your_DataFrame_is_bigger,_use_the_`set_option`_function_as_shown_in_the_example_below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns',_100)\\n", "pd.set_option('display.max_rows',_100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall_that_each_row_corresponds_to_one_client,_an_**instance**,_and_columns_are_**features**_of_this_instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s_have_a_look_at_data_dimensionality', 'feature_names', 'and_feature_types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', '20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From_the_output', 'we_can_see_that_the_table_contains_3333_rows_and_20_columns.\\n"', '\\n.15', "Now_let's_try_printing_out_column_names_using_`columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', "'Account_length'", "'Area_code'", "'International_plan'", '\\n"', "'Voice_mail_plan',_'Number_vmail_messages',_'Total_day_minutes',\\n", "'Total_day_calls',_'Total_day_charge',_'Total_eve_minutes',\\n", "'Total_eve_calls',_'Total_eve_charge',_'Total_night_minutes',\\n", "'Total_night_calls',_'Total_night_charge',_'Total_intl_minutes',\\n", "'Total_intl_calls',_'Total_intl_charge',_'Customer_service_calls',\\n", "'Churn'],\\n", "dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We_can_use_the_`info()`_method_to_output_some_general_information_about_the_dataframe:_"]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class_\'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex:_3333_entries,_0_to_3332\\n', 'Data_columns_(total_20_columns):\\n', '#___Column__________________Non-Null_Count__Dtype__\\n', '---__------__________________--------------__-----__\\n', '0___State___________________3333_non-null___object_\\n', '1___Account_length__________3333_non-null___int64__\\n', '2___Area_code_______________3333_non-null___int64__\\n', '3___International_plan______3333_non-null___object_\\n', '4___Voice_mail_plan_________3333_non-null___object_\\n', '5___Number_vmail_messages___3333_non-null___int64__\\n', '6___Total_day_minutes_______3333_non-null___float64\\n', '7___Total_day_calls_________3333_non-null___int64__\\n', '8___Total_day_charge________3333_non-null___float64\\n', '9___Total_eve_minutes_______3333_non-null___float64\\n', '10__Total_eve_calls_________3333_non-null___int64__\\n', '11__Total_eve_charge________3333_non-null___float64\\n', '12__Total_night_minutes_____3333_non-null___float64\\n', '13__Total_night_calls_______3333_non-null___int64__\\n', '14__Total_night_charge______3333_non-null___float64\\n', '15__Total_intl_minutes______3333_non-null___float64\\n', '16__Total_intl_calls________3333_non-null___int64__\\n', '17__Total_intl_charge_______3333_non-null___float64\\n', '18__Customer_service_calls__3333_non-null___int64__\\n', '19__Churn___________________3333_non-null___bool___\\n', 'dtypes:_bool(1),_float64(8),_int64(8),_object(3)\\n', 'memory_usage:_498.1+_KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', '`int64`', '`float64`_and_`object`_are_the_data_types_of_our_features._We_see_that_one_feature_is_logical_(`bool`)', '3_features_are_of_type_`object`', 'and_16_features_are_numeric._With_this_same_method', 'we_can_easily_see_if_there_are_any_missing_values._Here', 'there_are_none_because_each_column_contains_3333_observations', 'the_same_number_of_rows_we_saw_before_with_`shape`.\\n"', '\\n.16', "We_can_**change_the_column_type**_with_the_`astype`_method._Let's_apply_this_method_to_the_`Churn`_feature_to_convert_it_into_`int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"]_=_df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:"2021-05-07T08:36:00.714887"', 'exception:false.15', 'start_time:"2021-05-07T08:36:00.669434"', 'status:"completed"}.15', 'tags:[]}.15', 'source:["The_`describe`_method_shows_basic_statistical_characteristics_of_each_numerical_feature_(`int64`_and_`float64`_types):_number_of_non-missing_values', 'mean', 'standard_deviation', 'range', 'median', '0.25_and_0.75_quartiles."]}', '{"cell_type":"code".6', 'execution_count:7', 'id:"improving-spencer"', 'metadata:{"_uuid":"24e1d394f938980403a736421b4cf855ddb8ef8c"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.813975Z"', 'iopub.status.busy:"2021-05-07T08:36:00.813039Z"', 'iopub.status.idle:"2021-05-07T08:36:00.874306Z"', 'shell.execute_reply:"2021-05-07T08:36:00.874785Z"}', 'papermill:{"duration":0.113807', 'end_time:"2021-05-07T08:36:00.874959"', 'exception:false.16', 'start_time:"2021-05-07T08:36:00.761152"', 'status:"completed"}.16', 'tags:[]}.16', 'outputs:[{"data":{"text/html":["<div>\\n".1', '

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img_src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '\\n', '##_[mlcourse.ai](https://mlcourse.ai)_–_Open_Machine_Learning_Course_\\n', '\\n', 'Author:_[Yury_Kashnitsky](https://yorko.github.io)._Translated_and_edited_by_[Christina_Butsko](https://www.linkedin.com/in/christinabutsko/),_[Yuanyuan_Pao](https://www.linkedin.com/in/yuanyuanpao/),_[Anastasia_Manokhina](https://www.linkedin.com/in/anastasiamanokhina),_Sergey_Isaev,_and_[Artem_Trunov](https://www.linkedin.com/in/datamove/)._This_material_is_subject_to_the_terms_and_conditions_of_the_[Creative_Commons_CC_BY-NC-SA_4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)_license._Free_use_is_permitted_for_any_non-commercial_purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["#_<center>_Topic_1._Exploratory_data_analysis_with_Pandas\\n"', '\\n.1', '<img_align=\\center\\"_src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"__width=50%_/>\\n"', '\\n.2', '##_Article_outline\\n', '1._[Demonstration_of_main_Pandas_methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2._[First_attempt_at_predicting_telecom_churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3._[Assignments](#3.-Assignments)\\n', '4._[Useful_resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["##_1._Demonstration_of_main_Pandas_methods\\n"', 'Well..._There_are_dozens_of_cool_tutorials_on_Pandas_and_visual_data_analysis._If_you_are_already_familiar_with_these_topics,_you_can_wait_for_the_3rd_article_in_the_series,_where_we_get_into_machine_learning.__\\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)**_is_a_Python_library_that_provides_extensive_means_for_data_analysis._Data_scientists_often_work_with_data_stored_in_table_formats_like_`.csv`,_`.tsv`,_or_`.xlsx`._Pandas_makes_it_very_convenient_to_load,_process,_and_analyze_such_tabular_data_using_SQL-like_queries._In_conjunction_with_`Matplotlib`_and_`Seaborn`,_`Pandas`_provides_a_wide_range_of_opportunities_for_visual_analysis_of_tabular_data.\\n', '\\n.4', 'The_main_data_structures_in_`Pandas`_are_implemented_with_**Series**_and_**DataFrame**_classes._The_former_is_a_one-dimensional_indexed_array_of_some_fixed_data_type._The_latter_is_a_two-dimensional_data_structure_-_a_table_-_where_each_column_contains_data_of_the_same_type._You_can_see_it_as_a_dictionary_of_`Series`_instances._`DataFrames`_are_great_for_representing_real_data:_rows_correspond_to_instances_(examples,_observations,_etc.),_and_columns_correspond_to_features_of_these_instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import_numpy_as_np\\n"', 'import_pandas_as_pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', '2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll_demonstrate_the_main_methods_in_action_by_analyzing_a_[dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383)_on_the_churn_rate_of_telecom_operator_clients._Let\'s_read_the_data_(using_`read_csv`)', 'and_take_a_look_at_the_first_5_lines_using_the_`head`_method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style_scoped>\\n', '.dataframe_tbody_tr_th:only-of-type_{\\n', 'vertical-align:_middle;\\n', '}\\n', '\\n.6', '.dataframe_tbody_tr_th_{\\n', 'vertical-align:_top;\\n', '}\\n.1', '\\n.7', '.dataframe_thead_th_{\\n', 'text-align:_right;\\n', '}\\n.2', '</style>\\n', '<table_border=\\1\\"_class=\\"dataframe\\">\\n"', '<thead>\\n', '<tr_style=\\text-align:_right;\\">\\n"', '<th></th>\\n', '<th>State</th>\\n', '<th>Account_length</th>\\n', '<th>Area_code</th>\\n', '<th>International_plan</th>\\n', '<th>Voice_mail_plan</th>\\n', '<th>Number_vmail_messages</th>\\n', '<th>Total_day_minutes</th>\\n', '<th>Total_day_calls</th>\\n', '<th>Total_day_charge</th>\\n', '<th>Total_eve_minutes</th>\\n', '<th>Total_eve_calls</th>\\n', '<th>Total_eve_charge</th>\\n', '<th>Total_night_minutes</th>\\n', '<th>Total_night_calls</th>\\n', '<th>Total_night_charge</th>\\n', '<th>Total_intl_minutes</th>\\n', '<th>Total_intl_calls</th>\\n', '<th>Total_intl_charge</th>\\n', '<th>Customer_service_calls</th>\\n', '<th>Churn</th>\\n', '</tr>\\n', '</thead>\\n', '<tbody>\\n', '<tr>\\n', '<th>0</th>\\n', '<td>KS</td>\\n', '<td>128</td>\\n', '<td>415</td>\\n', '<td>No</td>\\n', '<td>Yes</td>\\n', '<td>25</td>\\n', '<td>265.1</td>\\n', '<td>110</td>\\n', '<td>45.07</td>\\n', '<td>197.4</td>\\n', '<td>99</td>\\n', '<td>16.78</td>\\n', '<td>244.7</td>\\n', '<td>91</td>\\n', '<td>11.01</td>\\n', '<td>10.0</td>\\n', '<td>3</td>\\n', '<td>2.70</td>\\n', '<td>1</td>\\n', '<td>False</td>\\n', '</tr>\\n.1', '<tr>\\n.1', '<th>1</th>\\n', '<td>OH</td>\\n', '<td>107</td>\\n', '<td>415</td>\\n.1', '<td>No</td>\\n.1', '<td>Yes</td>\\n.1', '<td>26</td>\\n', '<td>161.6</td>\\n', '<td>123</td>\\n', '<td>27.47</td>\\n', '<td>195.5</td>\\n', '<td>103</td>\\n', '<td>16.62</td>\\n', '<td>254.4</td>\\n', '<td>103</td>\\n.1', '<td>11.45</td>\\n', '<td>13.7</td>\\n', '<td>3</td>\\n.1', '<td>3.70</td>\\n', '<td>1</td>\\n.1', '<td>False</td>\\n.1', '</tr>\\n.2', '<tr>\\n.2', '<th>2</th>\\n', '<td>NJ</td>\\n', '<td>137</td>\\n', '<td>415</td>\\n.2', '<td>No</td>\\n.2', '<td>No</td>\\n.3', '<td>0</td>\\n', '<td>243.4</td>\\n', '<td>114</td>\\n', '<td>41.38</td>\\n', '<td>121.2</td>\\n', '<td>110</td>\\n.1', '<td>10.30</td>\\n', '<td>162.6</td>\\n', '<td>104</td>\\n', '<td>7.32</td>\\n', '<td>12.2</td>\\n', '<td>5</td>\\n', '<td>3.29</td>\\n', '<td>0</td>\\n.1', '<td>False</td>\\n.2', '</tr>\\n.3', '<tr>\\n.3', '<th>3</th>\\n', '<td>OH</td>\\n.1', '<td>84</td>\\n', '<td>408</td>\\n', '<td>Yes</td>\\n.2', '<td>No</td>\\n.4', '<td>0</td>\\n.2', '<td>299.4</td>\\n', '<td>71</td>\\n', '<td>50.90</td>\\n', '<td>61.9</td>\\n', '<td>88</td>\\n', '<td>5.26</td>\\n', '<td>196.9</td>\\n', '<td>89</td>\\n', '<td>8.86</td>\\n', '<td>6.6</td>\\n', '<td>7</td>\\n', '<td>1.78</td>\\n', '<td>2</td>\\n', '<td>False</td>\\n.3', '</tr>\\n.4', '<tr>\\n.4', '<th>4</th>\\n', '<td>OK</td>\\n', '<td>75</td>\\n', '<td>415</td>\\n.3', '<td>Yes</td>\\n.3', '<td>No</td>\\n.5', '<td>0</td>\\n.3', '<td>166.7</td>\\n', '<td>113</td>\\n', '<td>28.34</td>\\n', '<td>148.3</td>\\n', '<td>122</td>\\n', '<td>12.61</td>\\n', '<td>186.9</td>\\n', '<td>121</td>\\n', '<td>8.41</td>\\n', '<td>10.1</td>\\n', '<td>3</td>\\n.2', '<td>2.73</td>\\n', '<td>3</td>\\n.3', '<td>False</td>\\n.4', '</tr>\\n.5', '</tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["__State__Account_length__Area_code_International_plan_Voice_mail_plan__\\\\\\n"', '0____KS_____________128________415_________________No_____________Yes___\\n', '1____OH_____________107________415_________________No_____________Yes___\\n', '2____NJ_____________137________415_________________No______________No___\\n', '3____OH______________84________408________________Yes______________No___\\n', '4____OK______________75________415________________Yes______________No___\\n', '\\n.8', 'Number_vmail_messages__Total_day_minutes__Total_day_calls__\\\\\\n', '0_____________________25______________265.1______________110___\\n', '1_____________________26______________161.6______________123___\\n', '2______________________0______________243.4______________114___\\n', '3______________________0______________299.4_______________71___\\n', '4______________________0______________166.7______________113___\\n', '\\n.9', 'Total_day_charge__Total_eve_minutes__Total_eve_calls__Total_eve_charge__\\\\\\n', '0_____________45.07______________197.4_______________99_____________16.78___\\n', '1_____________27.47______________195.5______________103_____________16.62___\\n', '2_____________41.38______________121.2______________110_____________10.30___\\n', '3_____________50.90_______________61.9_______________88______________5.26___\\n', '4_____________28.34______________148.3______________122_____________12.61___\\n', '\\n.10', 'Total_night_minutes__Total_night_calls__Total_night_charge__\\\\\\n', '0________________244.7_________________91_______________11.01___\\n', '1________________254.4________________103_______________11.45___\\n', '2________________162.6________________104________________7.32___\\n', '3________________196.9_________________89________________8.86___\\n', '4________________186.9________________121________________8.41___\\n', '\\n.11', 'Total_intl_minutes__Total_intl_calls__Total_intl_charge__\\\\\\n', '0________________10.0_________________3_______________2.70___\\n', '1________________13.7_________________3_______________3.70___\\n', '2________________12.2_________________5_______________3.29___\\n', '3_________________6.6_________________7_______________1.78___\\n', '4________________10.1_________________3_______________2.73___\\n', '\\n.12', 'Customer_service_calls__Churn__\\n', '0_______________________1__False__\\n', '1_______________________1__False__\\n', '2_______________________0__False__\\n', '3_______________________2__False__\\n', '4_______________________3__False__]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df_=_pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About_printing_DataFrames_in_Jupyter_notebooks</summary>\\n', '<p>\\n', 'In_Jupyter_notebooks,_Pandas_DataFrames_are_printed_as_these_pretty_tables_seen_above_while_`print(df.head())`_is_less_nicely_formatted.\\n', 'By_default,_Pandas_displays_20_columns_and_60_rows,_so,_if_your_DataFrame_is_bigger,_use_the_`set_option`_function_as_shown_in_the_example_below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns',_100)\\n", "pd.set_option('display.max_rows',_100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall_that_each_row_corresponds_to_one_client,_an_**instance**,_and_columns_are_**features**_of_this_instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s_have_a_look_at_data_dimensionality', 'feature_names', 'and_feature_types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', '20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From_the_output', 'we_can_see_that_the_table_contains_3333_rows_and_20_columns.\\n"', '\\n.15', "Now_let's_try_printing_out_column_names_using_`columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', "'Account_length'", "'Area_code'", "'International_plan'", '\\n"', "'Voice_mail_plan',_'Number_vmail_messages',_'Total_day_minutes',\\n", "'Total_day_calls',_'Total_day_charge',_'Total_eve_minutes',\\n", "'Total_eve_calls',_'Total_eve_charge',_'Total_night_minutes',\\n", "'Total_night_calls',_'Total_night_charge',_'Total_intl_minutes',\\n", "'Total_intl_calls',_'Total_intl_charge',_'Customer_service_calls',\\n", "'Churn'],\\n", "dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We_can_use_the_`info()`_method_to_output_some_general_information_about_the_dataframe:_"]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class_\'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex:_3333_entries,_0_to_3332\\n', 'Data_columns_(total_20_columns):\\n', '#___Column__________________Non-Null_Count__Dtype__\\n', '---__------__________________--------------__-----__\\n', '0___State___________________3333_non-null___object_\\n', '1___Account_length__________3333_non-null___int64__\\n', '2___Area_code_______________3333_non-null___int64__\\n', '3___International_plan______3333_non-null___object_\\n', '4___Voice_mail_plan_________3333_non-null___object_\\n', '5___Number_vmail_messages___3333_non-null___int64__\\n', '6___Total_day_minutes_______3333_non-null___float64\\n', '7___Total_day_calls_________3333_non-null___int64__\\n', '8___Total_day_charge________3333_non-null___float64\\n', '9___Total_eve_minutes_______3333_non-null___float64\\n', '10__Total_eve_calls_________3333_non-null___int64__\\n', '11__Total_eve_charge________3333_non-null___float64\\n', '12__Total_night_minutes_____3333_non-null___float64\\n', '13__Total_night_calls_______3333_non-null___int64__\\n', '14__Total_night_charge______3333_non-null___float64\\n', '15__Total_intl_minutes______3333_non-null___float64\\n', '16__Total_intl_calls________3333_non-null___int64__\\n', '17__Total_intl_charge_______3333_non-null___float64\\n', '18__Customer_service_calls__3333_non-null___int64__\\n', '19__Churn___________________3333_non-null___bool___\\n', 'dtypes:_bool(1),_float64(8),_int64(8),_object(3)\\n', 'memory_usage:_498.1+_KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', '`int64`', '`float64`_and_`object`_are_the_data_types_of_our_features._We_see_that_one_feature_is_logical_(`bool`)', '3_features_are_of_type_`object`', 'and_16_features_are_numeric._With_this_same_method', 'we_can_easily_see_if_there_are_any_missing_values._Here', 'there_are_none_because_each_column_contains_3333_observations', 'the_same_number_of_rows_we_saw_before_with_`shape`.\\n"', '\\n.16', "We_can_**change_the_column_type**_with_the_`astype`_method._Let's_apply_this_method_to_the_`Churn`_feature_to_convert_it_into_`int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"]_=_df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:"2021-05-07T08:36:00.714887"', 'exception:false.15', 'start_time:"2021-05-07T08:36:00.669434"', 'status:"completed"}.15', 'tags:[]}.15', 'source:["The_`describe`_method_shows_basic_statistical_characteristics_of_each_numerical_feature_(`int64`_and_`float64`_types):_number_of_non-missing_values', 'mean', 'standard_deviation', 'range', 'median', '0.25_and_0.75_quartiles."]}', '{"cell_type":"code".6', 'execution_count:7', 'id:"improving-spencer"', 'metadata:{"_uuid":"24e1d394f938980403a736421b4cf855ddb8ef8c"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.813975Z"', 'iopub.status.busy:"2021-05-07T08:36:00.813039Z"', 'iopub.status.idle:"2021-05-07T08:36:00.874306Z"', 'shell.execute_reply:"2021-05-07T08:36:00.874785Z"}', 'papermill:{"duration":0.113807', 'end_time:"2021-05-07T08:36:00.874959"', 'exception:false.16', 'start_time:"2021-05-07T08:36:00.761152"', 'status:"completed"}.16', 'tags:[]}.16', 'outputs:[{"data":{"text/html":["<div>\\n".1', '

In [ ]:
for i, col in enumerate(df.columns):
    print(i, repr(col))

0 '{"cells":[{"cell_type":"markdown"'
1 'id:"stretch-davis"'
2 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"'
3 'papermill:{"duration":0.04692'
4 'end_time:"2021-05-07T08:35:59.190175"'
5 'exception:false'
6 'start_time:"2021-05-07T08:35:59.143255"'
7 'status:"completed"}'
8 'tags:[]}'
9 'source:["<center>\\n"'
10 '<img_src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"'
11 '\\n'
12 '##_[mlcourse.ai](https://mlcourse.ai)_–_Open_Machine_Learning_Course_\\n'
13 '\\n'
14 'Author:_[Yury_Kashnitsky](https://yorko.github.io)._Translated_and_edited_by_[Christina_Butsko](https://www.linkedin.com/in/christinabutsko/),_[Yuanyuan_Pao](https://www.linkedin.com/in/yuanyuanpao/),_[Anastasia_Manokhina](https://www.linkedin.com/in/anastasiamanokhina),_Sergey_Isaev,_and_[Artem_Trunov](https://www.linkedin.com/in/datamove/)._This_material_is_subject_to_the_terms_and_conditions_of_the_[Creative_Commons_CC_BY-NC-SA_4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)_license._Free_use_is_permitted_for_any_non-commercial_purpose.]}'
15 '{"cell_type":"markdown"'
16 'id:"afraid-serum"'
17 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"'
18 'papermill:{"duration":0.04455'
19 'end_time:"2021-05-07T08:35:59.279099"'
20 'exception:false.1'
21 'start_time:"2021-05-07T08:35:59.234549"'
22 'status:"completed"}.1'
23 'tags:[]}.1'
24 'source:["#_<center>_Topic_1._Exploratory_data_analysis_with_Pandas\\n"'
25 '\\n.1'
26 '<img_align=\\center\\"_src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"__width=50%_/>\\n"'
27 '\\n.2'
28 '##_Article_outline\\n'
29 '1._[Demonstration_of_main_Pandas_methods](#1.-Demonstration-of-main-Pandas-methods)\\n'
30 '2._[First_attempt_at_predicting_telecom_churn](#2.-First-attempt-at-predicting-telecom-churn)\\n'
31 '3._[Assignments](#3.-Assignments)\\n'
32 '4._[Useful_resources](#4.-Useful-resources)]}'
33 '{"cell_type":"markdown".1'
34 'id:"optional-comparative"'
35 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"'
36 'papermill:{"duration":0.043036'
37 'end_time:"2021-05-07T08:35:59.367136"'
38 'exception:false.2'
39 'start_time:"2021-05-07T08:35:59.3241"'
40 'status:"completed"}.2'
41 'tags:[]}.2'
42 'source:["##_1._Demonstration_of_main_Pandas_methods\\n"'
43 'Well..._There_are_dozens_of_cool_tutorials_on_Pandas_and_visual_data_analysis._If_you_are_already_familiar_with_these_topics,_you_can_wait_for_the_3rd_article_in_the_series,_where_we_get_into_machine_learning.__\\n'
44 '\\n.3'
45 '**[Pandas](http://pandas.pydata.org)**_is_a_Python_library_that_provides_extensive_means_for_data_analysis._Data_scientists_often_work_with_data_stored_in_table_formats_like_`.csv`,_`.tsv`,_or_`.xlsx`._Pandas_makes_it_very_convenient_to_load,_process,_and_analyze_such_tabular_data_using_SQL-like_queries._In_conjunction_with_`Matplotlib`_and_`Seaborn`,_`Pandas`_provides_a_wide_range_of_opportunities_for_visual_analysis_of_tabular_data.\\n'
46 '\\n.4'
47 'The_main_data_structures_in_`Pandas`_are_implemented_with_**Series**_and_**DataFrame**_classes._The_former_is_a_one-dimensional_indexed_array_of_some_fixed_data_type._The_latter_is_a_two-dimensional_data_structure_-_a_table_-_where_each_column_contains_data_of_the_same_type._You_can_see_it_as_a_dictionary_of_`Series`_instances._`DataFrames`_are_great_for_representing_real_data:_rows_correspond_to_instances_(examples,_observations,_etc.),_and_columns_correspond_to_features_of_these_instances.]}'
48 '{"cell_type":"code"'
49 'execution_count:1'
50 'id:"supreme-beatles"'
51 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"'
52 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"'
53 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"'
54 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"'
55 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}'
56 'papermill:{"duration":0.052221'
57 'end_time:"2021-05-07T08:35:59.463863"'
58 'exception:false.3'
59 'start_time:"2021-05-07T08:35:59.411642"'
60 'status:"completed"}.3'
61 'tags:[]}.3'
62 'outputs:[]'
63 'source:["import_numpy_as_np\\n"'
64 'import_pandas_as_pd\\n'
65 '\\n.5'
66 'pd.set_option(\\display.precision\\"'
67 '2)"]}'
68 '{"cell_type":"markdown".2'
69 'id:"catholic-remainder"'
70 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"'
71 'papermill:{"duration":0.045851'
72 'end_time:"2021-05-07T08:35:59.553832"'
73 'exception:false.4'
74 'start_time:"2021-05-07T08:35:59.507981"'
75 'status:"completed"}.4'
76 'tags:[]}.4'
77 'source:["We\'ll_demonstrate_the_main_methods_in_action_by_analyzing_a_[dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383)_on_the_churn_rate_of_telecom_operator_clients._Let\'s_read_the_data_(using_`read_csv`)'
78 'and_take_a_look_at_the_first_5_lines_using_the_`head`_method:"]}'
79 '{"cell_type":"code".1'
80 'execution_count:2'
81 'id:"interesting-dodge"'
82 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"'
83 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"'
84 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"'
85 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"'
86 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}'
87 'papermill:{"duration":0.13323'
88 'end_time:"2021-05-07T08:35:59.731738"'
89 'exception:false.5'
90 'start_time:"2021-05-07T08:35:59.598508"'
91 'status:"completed"}.5'
92 'tags:[]}.5'
93 'outputs:[{"data":{"text/html":["<div>\\n"'
94 '<style_scoped>\\n'
95 '.dataframe_tbody_tr_th:only-of-type_{\\n'
96 'vertical-align:_middle;\\n'
97 '}\\n'
98 '\\n.6'
99 '.dataframe_tbody_tr_th_{\\n'
100 'vertical-align:_top;\\n'
101 '}\\n.1'
102 '\\n.7'
103 '.dataframe_thead_th_{\\n'
104 'text-align:_right;\\n'
105 '}\\n.2'
106 '</style>\\n'
107 '<table_border=\\1\\"_class=\\"dataframe\\">\\n"'
108 '<thead>\\n'
109 '<tr_style=\\text-align:_right;\\">\\n"'
110 '<th></th>\\n'
111 '<th>State</th>\\n'
112 '<th>Account_length</th>\\n'
113 '<th>Area_code</th>\\n'
114 '<th>International_plan</th>\\n'
115 '<th>Voice_mail_plan</th>\\n'
116 '<th>Number_vmail_messages</th>\\n'
117 '<th>Total_day_minutes</th>\\n'
118 '<th>Total_day_calls</th>\\n'
119 '<th>Total_day_charge</th>\\n'
120 '<th>Total_eve_minutes</th>\\n'
121 '<th>Total_eve_calls</th>\\n'
122 '<th>Total_eve_charge</th>\\n'
123 '<th>Total_night_minutes</th>\\n'
124 '<th>Total_night_calls</th>\\n'
125 '<th>Total_night_charge</th>\\n'
126 '<th>Total_intl_minutes</th>\\n'
127 '<th>Total_intl_calls</th>\\n'
128 '<th>Total_intl_charge</th>\\n'
129 '<th>Customer_service_calls</th>\\n'
130 '<th>Churn</th>\\n'
131 '</tr>\\n'
132 '</thead>\\n'
133 '<tbody>\\n'
134 '<tr>\\n'
135 '<th>0</th>\\n'
136 '<td>KS</td>\\n'
137 '<td>128</td>\\n'
138 '<td>415</td>\\n'
139 '<td>No</td>\\n'
140 '<td>Yes</td>\\n'
141 '<td>25</td>\\n'
142 '<td>265.1</td>\\n'
143 '<td>110</td>\\n'
144 '<td>45.07</td>\\n'
145 '<td>197.4</td>\\n'
146 '<td>99</td>\\n'
147 '<td>16.78</td>\\n'
148 '<td>244.7</td>\\n'
149 '<td>91</td>\\n'
150 '<td>11.01</td>\\n'
151 '<td>10.0</td>\\n'
152 '<td>3</td>\\n'
153 '<td>2.70</td>\\n'
154 '<td>1</td>\\n'
155 '<td>False</td>\\n'
156 '</tr>\\n.1'
157 '<tr>\\n.1'
158 '<th>1</th>\\n'
159 '<td>OH</td>\\n'
160 '<td>107</td>\\n'
161 '<td>415</td>\\n.1'
162 '<td>No</td>\\n.1'
163 '<td>Yes</td>\\n.1'
164 '<td>26</td>\\n'
165 '<td>161.6</td>\\n'
166 '<td>123</td>\\n'
167 '<td>27.47</td>\\n'
168 '<td>195.5</td>\\n'
169 '<td>103</td>\\n'
170 '<td>16.62</td>\\n'
171 '<td>254.4</td>\\n'
172 '<td>103</td>\\n.1'
173 '<td>11.45</td>\\n'
174 '<td>13.7</td>\\n'
175 '<td>3</td>\\n.1'
176 '<td>3.70</td>\\n'
177 '<td>1</td>\\n.1'
178 '<td>False</td>\\n.1'
179 '</tr>\\n.2'
180 '<tr>\\n.2'
181 '<th>2</th>\\n'
182 '<td>NJ</td>\\n'
183 '<td>137</td>\\n'
184 '<td>415</td>\\n.2'
185 '<td>No</td>\\n.2'
186 '<td>No</td>\\n.3'
187 '<td>0</td>\\n'
188 '<td>243.4</td>\\n'
189 '<td>114</td>\\n'
190 '<td>41.38</td>\\n'
191 '<td>121.2</td>\\n'
192 '<td>110</td>\\n.1'
193 '<td>10.30</td>\\n'
194 '<td>162.6</td>\\n'
195 '<td>104</td>\\n'
196 '<td>7.32</td>\\n'
197 '<td>12.2</td>\\n'
198 '<td>5</td>\\n'
199 '<td>3.29</td>\\n'
200 '<td>0</td>\\n.1'
201 '<td>False</td>\\n.2'
202 '</tr>\\n.3'
203 '<tr>\\n.3'
204 '<th>3</th>\\n'
205 '<td>OH</td>\\n.1'
206 '<td>84</td>\\n'
207 '<td>408</td>\\n'
208 '<td>Yes</td>\\n.2'
209 '<td>No</td>\\n.4'
210 '<td>0</td>\\n.2'
211 '<td>299.4</td>\\n'
212 '<td>71</td>\\n'
213 '<td>50.90</td>\\n'
214 '<td>61.9</td>\\n'
215 '<td>88</td>\\n'
216 '<td>5.26</td>\\n'
217 '<td>196.9</td>\\n'
218 '<td>89</td>\\n'
219 '<td>8.86</td>\\n'
220 '<td>6.6</td>\\n'
221 '<td>7</td>\\n'
222 '<td>1.78</td>\\n'
223 '<td>2</td>\\n'
224 '<td>False</td>\\n.3'
225 '</tr>\\n.4'
226 '<tr>\\n.4'
227 '<th>4</th>\\n'
228 '<td>OK</td>\\n'
229 '<td>75</td>\\n'
230 '<td>415</td>\\n.3'
231 '<td>Yes</td>\\n.3'
232 '<td>No</td>\\n.5'
233 '<td>0</td>\\n.3'
234 '<td>166.7</td>\\n'
235 '<td>113</td>\\n'
236 '<td>28.34</td>\\n'
237 '<td>148.3</td>\\n'
238 '<td>122</td>\\n'
239 '<td>12.61</td>\\n'
240 '<td>186.9</td>\\n'
241 '<td>121</td>\\n'
242 '<td>8.41</td>\\n'
243 '<td>10.1</td>\\n'
244 '<td>3</td>\\n.2'
245 '<td>2.73</td>\\n'
246 '<td>3</td>\\n.3'
247 '<td>False</td>\\n.4'
248 '</tr>\\n.5'
249 '</tbody>\\n'
250 '</table>\\n'
251 '</div>]'
252 'text/plain:["__State__Account_length__Area_code_International_plan_Voice_mail_plan__\\\\\\n"'
253 '0____KS_____________128________415_________________No_____________Yes___\\n'
254 '1____OH_____________107________415_________________No_____________Yes___\\n'
255 '2____NJ_____________137________415_________________No______________No___\\n'
256 '3____OH______________84________408________________Yes______________No___\\n'
257 '4____OK______________75________415________________Yes______________No___\\n'
258 '\\n.8'
259 'Number_vmail_messages__Total_day_minutes__Total_day_calls__\\\\\\n'
260 '0_____________________25______________265.1______________110___\\n'
261 '1_____________________26______________161.6______________123___\\n'
262 '2______________________0______________243.4______________114___\\n'
263 '3______________________0______________299.4_______________71___\\n'
264 '4______________________0______________166.7______________113___\\n'
265 '\\n.9'
266 'Total_day_charge__Total_eve_minutes__Total_eve_calls__Total_eve_charge__\\\\\\n'
267 '0_____________45.07______________197.4_______________99_____________16.78___\\n'
268 '1_____________27.47______________195.5______________103_____________16.62___\\n'
269 '2_____________41.38______________121.2______________110_____________10.30___\\n'
270 '3_____________50.90_______________61.9_______________88______________5.26___\\n'
271 '4_____________28.34______________148.3______________122_____________12.61___\\n'
272 '\\n.10'
273 'Total_night_minutes__Total_night_calls__Total_night_charge__\\\\\\n'
274 '0________________244.7_________________91_______________11.01___\\n'
275 '1________________254.4________________103_______________11.45___\\n'
276 '2________________162.6________________104________________7.32___\\n'
277 '3________________196.9_________________89________________8.86___\\n'
278 '4________________186.9________________121________________8.41___\\n'
279 '\\n.11'
280 'Total_intl_minutes__Total_intl_calls__Total_intl_charge__\\\\\\n'
281 '0________________10.0_________________3_______________2.70___\\n'
282 '1________________13.7_________________3_______________3.70___\\n'
283 '2________________12.2_________________5_______________3.29___\\n'
284 '3_________________6.6_________________7_______________1.78___\\n'
285 '4________________10.1_________________3_______________2.73___\\n'
286 '\\n.12'
287 'Customer_service_calls__Churn__\\n'
288 '0_______________________1__False__\\n'
289 '1_______________________1__False__\\n'
290 '2_______________________0__False__\\n'
291 '3_______________________2__False__\\n'
292 '4_______________________3__False__]}'
293 'execution_count:2.1'
294 'metadata:{}'
295 'output_type:"execute_result"}]'
296 'source:["df_=_pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"'
297 'df.head()]}'
298 '{"cell_type":"markdown".3'
299 'id:"opposite-simulation"'
300 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"'
301 'papermill:{"duration":0.045163'
302 'end_time:"2021-05-07T08:35:59.823093"'
303 'exception:false.6'
304 'start_time:"2021-05-07T08:35:59.77793"'
305 'status:"completed"}.6'
306 'tags:[]}.6'
307 'source:["<details>\\n"'
308 '<summary>About_printing_DataFrames_in_Jupyter_notebooks</summary>\\n'
309 '<p>\\n'
310 'In_Jupyter_notebooks,_Pandas_DataFrames_are_printed_as_these_pretty_tables_seen_above_while_`print(df.head())`_is_less_nicely_formatted.\\n'
311 'By_default,_Pandas_displays_20_columns_and_60_rows,_so,_if_your_DataFrame_is_bigger,_use_the_`set_option`_function_as_shown_in_the_example_below:\\n'
312 '\\n.13'
313 '```python\\n'
314 "pd.set_option('display.max_columns',_100)\\n"
315 "pd.set_option('display.max_rows',_100)\\n"
316 '```\\n'
317 '</p>\\n'
318 '</details>\\n'
319 '\\n.14'
320 'Recall_that_each_row_corresponds_to_one_client,_an_**instance**,_and_columns_are_**features**_of_this_instance.]}'
321 '{"cell_type":"markdown".4'
322 'id:"going-wealth"'
323 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"'
324 'papermill:{"duration":0.045703'
325 'end_time:"2021-05-07T08:35:59.91464"'
326 'exception:false.7'
327 'start_time:"2021-05-07T08:35:59.868937"'
328 'status:"completed"}.7'
329 'tags:[]}.7'
330 'source:["Let’s_have_a_look_at_data_dimensionality'
331 'feature_names'
332 'and_feature_types."]}'
333 '{"cell_type":"code".2'
334 'execution_count:3'
335 'id:"inside-stephen"'
336 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"'
337 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"'
338 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"'
339 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"'
340 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}'
341 'papermill:{"duration":0.055704'
342 'end_time:"2021-05-07T08:36:00.015548"'
343 'exception:false.8'
344 'start_time:"2021-05-07T08:35:59.959844"'
345 'status:"completed"}.8'
346 'tags:[]}.8'
347 'outputs:[{"name":"stdout"'
348 'output_type:"stream"'
349 'text:["(3333'
350 '20)\\n"]}]'
351 'source:["print(df.shape)"]}'
352 '{"cell_type":"markdown".5'
353 'id:"collaborative-memphis"'
354 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"'
355 'papermill:{"duration":0.046317'
356 'end_time:"2021-05-07T08:36:00.108954"'
357 'exception:false.9'
358 'start_time:"2021-05-07T08:36:00.062637"'
359 'status:"completed"}.9'
360 'tags:[]}.9'
361 'source:["From_the_output'
362 'we_can_see_that_the_table_contains_3333_rows_and_20_columns.\\n"'
363 '\\n.15'
364 "Now_let's_try_printing_out_column_names_using_`columns`:]}"
365 '{"cell_type":"code".3'
366 'execution_count:4'
367 'id:"third-teach"'
368 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"'
369 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"'
370 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"'
371 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"'
372 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}'
373 'papermill:{"duration":0.055147'
374 'end_time:"2021-05-07T08:36:00.209149"'
375 'exception:false.10'
376 'start_time:"2021-05-07T08:36:00.154002"'
377 'status:"completed"}.10'
378 'tags:[]}.10'
379 'outputs:[{"name":"stdout".1'
380 'output_type:"stream".1'
381 'text:["Index([\'State\''
382 "'Account_length'"
383 "'Area_code'"
384 "'International_plan'"
385 '\\n"'
386 "'Voice_mail_plan',_'Number_vmail_messages',_'Total_day_minutes',\\n"
387 "'Total_day_calls',_'Total_day_charge',_'Total_eve_minutes',\\n"
388 "'Total_eve_calls',_'Total_eve_charge',_'Total_night_minutes',\\n"
389 "'Total_night_calls',_'Total_night_charge',_'Total_intl_minutes',\\n"
390 "'Total_intl_calls',_'Total_intl_charge',_'Customer_service_calls',\\n"
391 "'Churn'],\\n"
392 "dtype='object')\\n]}]"
393 'source:["print(df.columns)"]}'
394 '{"cell_type":"markdown".6'
395 'id:"interim-indonesian"'
396 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"'
397 'papermill:{"duration":0.047694'
398 'end_time:"2021-05-07T08:36:00.30581"'
399 'exception:false.11'
400 'start_time:"2021-05-07T08:36:00.258116"'
401 'status:"completed"}.11'
402 'tags:[]}.11'
403 'source:["We_can_use_the_`info()`_method_to_output_some_general_information_about_the_dataframe:_"]}'
404 '{"cell_type":"code".4'
405 'execution_count:5'
406 'id:"bored-moldova"'
407 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"'
408 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"'
409 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"'
410 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"'
411 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}'
412 'papermill:{"duration":0.071027'
413 'end_time:"2021-05-07T08:36:00.423026"'
414 'exception:false.12'
415 'start_time:"2021-05-07T08:36:00.351999"'
416 'status:"completed"}.12'
417 'tags:[]}.12'
418 'outputs:[{"name":"stdout".2'
419 'output_type:"stream".2'
420 'text:["<class_\'pandas.core.frame.DataFrame\'>\\n"'
421 'RangeIndex:_3333_entries,_0_to_3332\\n'
422 'Data_columns_(total_20_columns):\\n'
423 '#___Column__________________Non-Null_Count__Dtype__\\n'
424 '---__------__________________--------------__-----__\\n'
425 '0___State___________________3333_non-null___object_\\n'
426 '1___Account_length__________3333_non-null___int64__\\n'
427 '2___Area_code_______________3333_non-null___int64__\\n'
428 '3___International_plan______3333_non-null___object_\\n'
429 '4___Voice_mail_plan_________3333_non-null___object_\\n'
430 '5___Number_vmail_messages___3333_non-null___int64__\\n'
431 '6___Total_day_minutes_______3333_non-null___float64\\n'
432 '7___Total_day_calls_________3333_non-null___int64__\\n'
433 '8___Total_day_charge________3333_non-null___float64\\n'
434 '9___Total_eve_minutes_______3333_non-null___float64\\n'
435 '10__Total_eve_calls_________3333_non-null___int64__\\n'
436 '11__Total_eve_charge________3333_non-null___float64\\n'
437 '12__Total_night_minutes_____3333_non-null___float64\\n'
438 '13__Total_night_calls_______3333_non-null___int64__\\n'
439 '14__Total_night_charge______3333_non-null___float64\\n'
440 '15__Total_intl_minutes______3333_non-null___float64\\n'
441 '16__Total_intl_calls________3333_non-null___int64__\\n'
442 '17__Total_intl_charge_______3333_non-null___float64\\n'
443 '18__Customer_service_calls__3333_non-null___int64__\\n'
444 '19__Churn___________________3333_non-null___bool___\\n'
445 'dtypes:_bool(1),_float64(8),_int64(8),_object(3)\\n'
446 'memory_usage:_498.1+_KB\\n'
447 'None\\n]}]'
448 'source:["print(df.info())"]}'
449 '{"cell_type":"markdown".7'
450 'id:"desperate-leave"'
451 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"'
452 'papermill:{"duration":0.045853'
453 'end_time:"2021-05-07T08:36:00.515119"'
454 'exception:false.13'
455 'start_time:"2021-05-07T08:36:00.469266"'
456 'status:"completed"}.13'
457 'tags:[]}.13'
458 'source:["`bool`'
459 '`int64`'
460 '`float64`_and_`object`_are_the_data_types_of_our_features._We_see_that_one_feature_is_logical_(`bool`)'
461 '3_features_are_of_type_`object`'
462 'and_16_features_are_numeric._With_this_same_method'
463 'we_can_easily_see_if_there_are_any_missing_values._Here'
464 'there_are_none_because_each_column_contains_3333_observations'
465 'the_same_number_of_rows_we_saw_before_with_`shape`.\\n"'
466 '\\n.16'
467 "We_can_**change_the_column_type**_with_the_`astype`_method._Let's_apply_this_method_to_the_`Churn`_feature_to_convert_it_into_`int64`:]}"
468 '{"cell_type":"code".5'
469 'execution_count:6'
470 'id:"proprietary-novelty"'
471 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"'
472 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"'
473 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"'
474 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"'
475 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}'
476 'papermill:{"duration":0.059473'

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img_src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '\\n', '##_[mlcourse.ai](https://mlcourse.ai)_–_Open_Machine_Learning_Course_\\n', '\\n', 'Author:_[Yury_Kashnitsky](https://yorko.github.io)._Translated_and_edited_by_[Christina_Butsko](https://www.linkedin.com/in/christinabutsko/),_[Yuanyuan_Pao](https://www.linkedin.com/in/yuanyuanpao/),_[Anastasia_Manokhina](https://www.linkedin.com/in/anastasiamanokhina),_Sergey_Isaev,_and_[Artem_Trunov](https://www.linkedin.com/in/datamove/)._This_material_is_subject_to_the_terms_and_conditions_of_the_[Creative_Commons_CC_BY-NC-SA_4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)_license._Free_use_is_permitted_for_any_non-commercial_purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["#_<center>_Topic_1._Exploratory_data_analysis_with_Pandas\\n"', '\\n.1', '<img_align=\\center\\"_src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"__width=50%_/>\\n"', '\\n.2', '##_Article_outline\\n', '1._[Demonstration_of_main_Pandas_methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2._[First_attempt_at_predicting_telecom_churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3._[Assignments](#3.-Assignments)\\n', '4._[Useful_resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["##_1._Demonstration_of_main_Pandas_methods\\n"', 'Well..._There_are_dozens_of_cool_tutorials_on_Pandas_and_visual_data_analysis._If_you_are_already_familiar_with_these_topics,_you_can_wait_for_the_3rd_article_in_the_series,_where_we_get_into_machine_learning.__\\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)**_is_a_Python_library_that_provides_extensive_means_for_data_analysis._Data_scientists_often_work_with_data_stored_in_table_formats_like_`.csv`,_`.tsv`,_or_`.xlsx`._Pandas_makes_it_very_convenient_to_load,_process,_and_analyze_such_tabular_data_using_SQL-like_queries._In_conjunction_with_`Matplotlib`_and_`Seaborn`,_`Pandas`_provides_a_wide_range_of_opportunities_for_visual_analysis_of_tabular_data.\\n', '\\n.4', 'The_main_data_structures_in_`Pandas`_are_implemented_with_**Series**_and_**DataFrame**_classes._The_former_is_a_one-dimensional_indexed_array_of_some_fixed_data_type._The_latter_is_a_two-dimensional_data_structure_-_a_table_-_where_each_column_contains_data_of_the_same_type._You_can_see_it_as_a_dictionary_of_`Series`_instances._`DataFrames`_are_great_for_representing_real_data:_rows_correspond_to_instances_(examples,_observations,_etc.),_and_columns_correspond_to_features_of_these_instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import_numpy_as_np\\n"', 'import_pandas_as_pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', '2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll_demonstrate_the_main_methods_in_action_by_analyzing_a_[dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383)_on_the_churn_rate_of_telecom_operator_clients._Let\'s_read_the_data_(using_`read_csv`)', 'and_take_a_look_at_the_first_5_lines_using_the_`head`_method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style_scoped>\\n', '.dataframe_tbody_tr_th:only-of-type_{\\n', 'vertical-align:_middle;\\n', '}\\n', '\\n.6', '.dataframe_tbody_tr_th_{\\n', 'vertical-align:_top;\\n', '}\\n.1', '\\n.7', '.dataframe_thead_th_{\\n', 'text-align:_right;\\n', '}\\n.2', '</style>\\n', '<table_border=\\1\\"_class=\\"dataframe\\">\\n"', '<thead>\\n', '<tr_style=\\text-align:_right;\\">\\n"', '<th></th>\\n', '<th>State</th>\\n', '<th>Account_length</th>\\n', '<th>Area_code</th>\\n', '<th>International_plan</th>\\n', '<th>Voice_mail_plan</th>\\n', '<th>Number_vmail_messages</th>\\n', '<th>Total_day_minutes</th>\\n', '<th>Total_day_calls</th>\\n', '<th>Total_day_charge</th>\\n', '<th>Total_eve_minutes</th>\\n', '<th>Total_eve_calls</th>\\n', '<th>Total_eve_charge</th>\\n', '<th>Total_night_minutes</th>\\n', '<th>Total_night_calls</th>\\n', '<th>Total_night_charge</th>\\n', '<th>Total_intl_minutes</th>\\n', '<th>Total_intl_calls</th>\\n', '<th>Total_intl_charge</th>\\n', '<th>Customer_service_calls</th>\\n', '<th>Churn</th>\\n', '</tr>\\n', '</thead>\\n', '<tbody>\\n', '<tr>\\n', '<th>0</th>\\n', '<td>KS</td>\\n', '<td>128</td>\\n', '<td>415</td>\\n', '<td>No</td>\\n', '<td>Yes</td>\\n', '<td>25</td>\\n', '<td>265.1</td>\\n', '<td>110</td>\\n', '<td>45.07</td>\\n', '<td>197.4</td>\\n', '<td>99</td>\\n', '<td>16.78</td>\\n', '<td>244.7</td>\\n', '<td>91</td>\\n', '<td>11.01</td>\\n', '<td>10.0</td>\\n', '<td>3</td>\\n', '<td>2.70</td>\\n', '<td>1</td>\\n', '<td>False</td>\\n', '</tr>\\n.1', '<tr>\\n.1', '<th>1</th>\\n', '<td>OH</td>\\n', '<td>107</td>\\n', '<td>415</td>\\n.1', '<td>No</td>\\n.1', '<td>Yes</td>\\n.1', '<td>26</td>\\n', '<td>161.6</td>\\n', '<td>123</td>\\n', '<td>27.47</td>\\n', '<td>195.5</td>\\n', '<td>103</td>\\n', '<td>16.62</td>\\n', '<td>254.4</td>\\n', '<td>103</td>\\n.1', '<td>11.45</td>\\n', '<td>13.7</td>\\n', '<td>3</td>\\n.1', '<td>3.70</td>\\n', '<td>1</td>\\n.1', '<td>False</td>\\n.1', '</tr>\\n.2', '<tr>\\n.2', '<th>2</th>\\n', '<td>NJ</td>\\n', '<td>137</td>\\n', '<td>415</td>\\n.2', '<td>No</td>\\n.2', '<td>No</td>\\n.3', '<td>0</td>\\n', '<td>243.4</td>\\n', '<td>114</td>\\n', '<td>41.38</td>\\n', '<td>121.2</td>\\n', '<td>110</td>\\n.1', '<td>10.30</td>\\n', '<td>162.6</td>\\n', '<td>104</td>\\n', '<td>7.32</td>\\n', '<td>12.2</td>\\n', '<td>5</td>\\n', '<td>3.29</td>\\n', '<td>0</td>\\n.1', '<td>False</td>\\n.2', '</tr>\\n.3', '<tr>\\n.3', '<th>3</th>\\n', '<td>OH</td>\\n.1', '<td>84</td>\\n', '<td>408</td>\\n', '<td>Yes</td>\\n.2', '<td>No</td>\\n.4', '<td>0</td>\\n.2', '<td>299.4</td>\\n', '<td>71</td>\\n', '<td>50.90</td>\\n', '<td>61.9</td>\\n', '<td>88</td>\\n', '<td>5.26</td>\\n', '<td>196.9</td>\\n', '<td>89</td>\\n', '<td>8.86</td>\\n', '<td>6.6</td>\\n', '<td>7</td>\\n', '<td>1.78</td>\\n', '<td>2</td>\\n', '<td>False</td>\\n.3', '</tr>\\n.4', '<tr>\\n.4', '<th>4</th>\\n', '<td>OK</td>\\n', '<td>75</td>\\n', '<td>415</td>\\n.3', '<td>Yes</td>\\n.3', '<td>No</td>\\n.5', '<td>0</td>\\n.3', '<td>166.7</td>\\n', '<td>113</td>\\n', '<td>28.34</td>\\n', '<td>148.3</td>\\n', '<td>122</td>\\n', '<td>12.61</td>\\n', '<td>186.9</td>\\n', '<td>121</td>\\n', '<td>8.41</td>\\n', '<td>10.1</td>\\n', '<td>3</td>\\n.2', '<td>2.73</td>\\n', '<td>3</td>\\n.3', '<td>False</td>\\n.4', '</tr>\\n.5', '</tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["__State__Account_length__Area_code_International_plan_Voice_mail_plan__\\\\\\n"', '0____KS_____________128________415_________________No_____________Yes___\\n', '1____OH_____________107________415_________________No_____________Yes___\\n', '2____NJ_____________137________415_________________No______________No___\\n', '3____OH______________84________408________________Yes______________No___\\n', '4____OK______________75________415________________Yes______________No___\\n', '\\n.8', 'Number_vmail_messages__Total_day_minutes__Total_day_calls__\\\\\\n', '0_____________________25______________265.1______________110___\\n', '1_____________________26______________161.6______________123___\\n', '2______________________0______________243.4______________114___\\n', '3______________________0______________299.4_______________71___\\n', '4______________________0______________166.7______________113___\\n', '\\n.9', 'Total_day_charge__Total_eve_minutes__Total_eve_calls__Total_eve_charge__\\\\\\n', '0_____________45.07______________197.4_______________99_____________16.78___\\n', '1_____________27.47______________195.5______________103_____________16.62___\\n', '2_____________41.38______________121.2______________110_____________10.30___\\n', '3_____________50.90_______________61.9_______________88______________5.26___\\n', '4_____________28.34______________148.3______________122_____________12.61___\\n', '\\n.10', 'Total_night_minutes__Total_night_calls__Total_night_charge__\\\\\\n', '0________________244.7_________________91_______________11.01___\\n', '1________________254.4________________103_______________11.45___\\n', '2________________162.6________________104________________7.32___\\n', '3________________196.9_________________89________________8.86___\\n', '4________________186.9________________121________________8.41___\\n', '\\n.11', 'Total_intl_minutes__Total_intl_calls__Total_intl_charge__\\\\\\n', '0________________10.0_________________3_______________2.70___\\n', '1________________13.7_________________3_______________3.70___\\n', '2________________12.2_________________5_______________3.29___\\n', '3_________________6.6_________________7_______________1.78___\\n', '4________________10.1_________________3_______________2.73___\\n', '\\n.12', 'Customer_service_calls__Churn__\\n', '0_______________________1__False__\\n', '1_______________________1__False__\\n', '2_______________________0__False__\\n', '3_______________________2__False__\\n', '4_______________________3__False__]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df_=_pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About_printing_DataFrames_in_Jupyter_notebooks</summary>\\n', '<p>\\n', 'In_Jupyter_notebooks,_Pandas_DataFrames_are_printed_as_these_pretty_tables_seen_above_while_`print(df.head())`_is_less_nicely_formatted.\\n', 'By_default,_Pandas_displays_20_columns_and_60_rows,_so,_if_your_DataFrame_is_bigger,_use_the_`set_option`_function_as_shown_in_the_example_below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns',_100)\\n", "pd.set_option('display.max_rows',_100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall_that_each_row_corresponds_to_one_client,_an_**instance**,_and_columns_are_**features**_of_this_instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s_have_a_look_at_data_dimensionality', 'feature_names', 'and_feature_types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', '20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From_the_output', 'we_can_see_that_the_table_contains_3333_rows_and_20_columns.\\n"', '\\n.15', "Now_let's_try_printing_out_column_names_using_`columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', "'Account_length'", "'Area_code'", "'International_plan'", '\\n"', "'Voice_mail_plan',_'Number_vmail_messages',_'Total_day_minutes',\\n", "'Total_day_calls',_'Total_day_charge',_'Total_eve_minutes',\\n", "'Total_eve_calls',_'Total_eve_charge',_'Total_night_minutes',\\n", "'Total_night_calls',_'Total_night_charge',_'Total_intl_minutes',\\n", "'Total_intl_calls',_'Total_intl_charge',_'Customer_service_calls',\\n", "'Churn'],\\n", "dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We_can_use_the_`info()`_method_to_output_some_general_information_about_the_dataframe:_"]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class_\'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex:_3333_entries,_0_to_3332\\n', 'Data_columns_(total_20_columns):\\n', '#___Column__________________Non-Null_Count__Dtype__\\n', '---__------__________________--------------__-----__\\n', '0___State___________________3333_non-null___object_\\n', '1___Account_length__________3333_non-null___int64__\\n', '2___Area_code_______________3333_non-null___int64__\\n', '3___International_plan______3333_non-null___object_\\n', '4___Voice_mail_plan_________3333_non-null___object_\\n', '5___Number_vmail_messages___3333_non-null___int64__\\n', '6___Total_day_minutes_______3333_non-null___float64\\n', '7___Total_day_calls_________3333_non-null___int64__\\n', '8___Total_day_charge________3333_non-null___float64\\n', '9___Total_eve_minutes_______3333_non-null___float64\\n', '10__Total_eve_calls_________3333_non-null___int64__\\n', '11__Total_eve_charge________3333_non-null___float64\\n', '12__Total_night_minutes_____3333_non-null___float64\\n', '13__Total_night_calls_______3333_non-null___int64__\\n', '14__Total_night_charge______3333_non-null___float64\\n', '15__Total_intl_minutes______3333_non-null___float64\\n', '16__Total_intl_calls________3333_non-null___int64__\\n', '17__Total_intl_charge_______3333_non-null___float64\\n', '18__Customer_service_calls__3333_non-null___int64__\\n', '19__Churn___________________3333_non-null___bool___\\n', 'dtypes:_bool(1),_float64(8),_int64(8),_object(3)\\n', 'memory_usage:_498.1+_KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', '`int64`', '`float64`_and_`object`_are_the_data_types_of_our_features._We_see_that_one_feature_is_logical_(`bool`)', '3_features_are_of_type_`object`', 'and_16_features_are_numeric._With_this_same_method', 'we_can_easily_see_if_there_are_any_missing_values._Here', 'there_are_none_because_each_column_contains_3333_observations', 'the_same_number_of_rows_we_saw_before_with_`shape`.\\n"', '\\n.16', "We_can_**change_the_column_type**_with_the_`astype`_method._Let's_apply_this_method_to_the_`Churn`_feature_to_convert_it_into_`int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"]_=_df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:"2021-05-07T08:36:00.714887"', 'exception:false.15', 'start_time:"2021-05-07T08:36:00.669434"', 'status:"completed"}.15', 'tags:[]}.15', 'source:["The_`describe`_method_shows_basic_statistical_characteristics_of_each_numerical_feature_(`int64`_and_`float64`_types):_number_of_non-missing_values', 'mean', 'standard_deviation', 'range', 'median', '0.25_and_0.75_quartiles."]}', '{"cell_type":"code".6', 'execution_count:7', 'id:"improving-spencer"', 'metadata:{"_uuid":"24e1d394f938980403a736421b4cf855ddb8ef8c"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.813975Z"', 'iopub.status.busy:"2021-05-07T08:36:00.813039Z"', 'iopub.status.idle:"2021-05-07T08:36:00.874306Z"', 'shell.execute_reply:"2021-05-07T08:36:00.874785Z"}', 'papermill:{"duration":0.113807', 'end_time:"2021-05-07T08:36:00.874959"', 'exception:false.16', 'start_time:"2021-05-07T08:36:00.761152"', 'status:"completed"}.16', 'tags:[]}.16', 'outputs:[{"data":{"text/html":["<div>\\n".1', '

In [ ]:
import os

print(os.listdir('/content'))

['.config', '.ipynb_checkpoints', 'customer_churn.csv', 'sample_data']

In [ ]:
df = pd.read_csv('/content/customer_churn.csv')

In [ ]:
df.head()

Empty DataFrame
Columns: [{"cells":[{"cell_type":"markdown", id:"stretch-davis", metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935", papermill:{"duration":0.04692, end_time:"2021-05-07T08:35:59.190175", exception:false, start_time:"2021-05-07T08:35:59.143255", status:"completed"}, tags:[]}, source:["<center>\n", <img src=\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\">\n",     \n, ## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course \n, \n, Author: [Yury Kashnitsky](https://yorko.github.io). Translated and edited by [Christina Butsko](https://www.linkedin.com/in/christinabutsko/), [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina), Sergey Isaev, and [Artem Trunov](https://www.linkedin.com/in/datamove/). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.]}, {"cell_type":"markdown", id:"afraid-serum", metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668", papermill:{"duration":0.04455, end_time:"2021-05-07T08:35:59.279099", exception:false.1, start_time:"2021-05-07T08:35:59.234549", status:"completed"}.1, tags:[]}.1, source:["# <center> Topic 1. Exploratory data analysis with Pandas\n", \n.1, <img align=\center\" src=\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\"  width=50% />\n", \n.2, ## Article outline\n, 1. [Demonstration of main Pandas methods](#1.-Demonstration-of-main-Pandas-methods)\n, 2. [First attempt at predicting telecom churn](#2.-First-attempt-at-predicting-telecom-churn)\n, 3. [Assignments](#3.-Assignments)\n, 4. [Useful resources](#4.-Useful-resources)]}, {"cell_type":"markdown".1, id:"optional-comparative", metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649", papermill:{"duration":0.043036, end_time:"2021-05-07T08:35:59.367136", exception:false.2, start_time:"2021-05-07T08:35:59.3241", status:"completed"}.2, tags:[]}.2, source:["## 1. Demonstration of main Pandas methods\n", Well... There are dozens of cool tutorials on Pandas and visual data analysis. If you are already familiar with these topics, you can wait for the 3rd article in the series, where we get into machine learning.  \n, \n.3, **[Pandas](http://pandas.pydata.org)** is a Python library that provides extensive means for data analysis. Data scientists often work with data stored in table formats like `.csv`, `.tsv`, or `.xlsx`. Pandas makes it very convenient to load, process, and analyze such tabular data using SQL-like queries. In conjunction with `Matplotlib` and `Seaborn`, `Pandas` provides a wide range of opportunities for visual analysis of tabular data.\n, \n.4, The main data structures in `Pandas` are implemented with **Series** and **DataFrame** classes. The former is a one-dimensional indexed array of some fixed data type. The latter is a two-dimensional data structure - a table - where each column contains data of the same type. You can see it as a dictionary of `Series` instances. `DataFrames` are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.]}, {"cell_type":"code", execution_count:1, id:"supreme-beatles", metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4", execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z", iopub.status.busy:"2021-05-07T08:35:59.458289Z", iopub.status.idle:"2021-05-07T08:35:59.462927Z", shell.execute_reply:"2021-05-07T08:35:59.46356Z"}, papermill:{"duration":0.052221, end_time:"2021-05-07T08:35:59.463863", exception:false.3, start_time:"2021-05-07T08:35:59.411642", status:"completed"}.3, tags:[]}.3, outputs:[], source:["import numpy as np\n", import pandas as pd\n, \n.5, pd.set_option(\display.precision\",  2)"]}, {"cell_type":"markdown".2, id:"catholic-remainder", metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b", papermill:{"duration":0.045851, end_time:"2021-05-07T08:35:59.553832", exception:false.4, start_time:"2021-05-07T08:35:59.507981", status:"completed"}.4, tags:[]}.4, source:["We'll demonstrate the main methods in action by analyzing a [dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383) on the churn rate of telecom operator clients. Let's read the data (using `read_csv`),  and take a look at the first 5 lines using the `head` method:"]}, {"cell_type":"code".1, execution_count:2, id:"interesting-dodge", metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7", execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z", iopub.status.busy:"2021-05-07T08:35:59.645658Z", iopub.status.idle:"2021-05-07T08:35:59.731091Z", shell.execute_reply:"2021-05-07T08:35:59.731563Z"}, papermill:{"duration":0.13323, end_time:"2021-05-07T08:35:59.731738", exception:false.5, start_time:"2021-05-07T08:35:59.598508", status:"completed"}.5, tags:[]}.5, outputs:[{"data":{"text/html":["<div>\n", <style scoped>\n,     .dataframe tbody tr th:only-of-type {\n,         vertical-align: middle;\n,     }\n, \n.6,     .dataframe tbody tr th {\n, ...]
Index: []

[0 rows x 4452 columns]

In [ ]:
print(df.columns.tolist())

['{"cells":[{"cell_type":"markdown"', 'id:"stretch-davis"', 'metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"', 'papermill:{"duration":0.04692', 'end_time:"2021-05-07T08:35:59.190175"', 'exception:false', 'start_time:"2021-05-07T08:35:59.143255"', 'status:"completed"}', 'tags:[]}', 'source:["<center>\\n"', '<img src=\\https://habrastorage.org/webt/ia/m9/zk/iam9zkyzqebnf_okxipihkgjwnw.jpeg\\">\\n"', '    \\n', '## [mlcourse.ai](https://mlcourse.ai) – Open Machine Learning Course \\n', '\\n', 'Author: [Yury Kashnitsky](https://yorko.github.io). Translated and edited by [Christina Butsko](https://www.linkedin.com/in/christinabutsko/), [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina), Sergey Isaev, and [Artem Trunov](https://www.linkedin.com/in/datamove/). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.]}', '{"cell_type":"markdown"', 'id:"afraid-serum"', 'metadata:{"_uuid":"9b690f2c8129ad9445c544337375b93246c26668"', 'papermill:{"duration":0.04455', 'end_time:"2021-05-07T08:35:59.279099"', 'exception:false.1', 'start_time:"2021-05-07T08:35:59.234549"', 'status:"completed"}.1', 'tags:[]}.1', 'source:["# <center> Topic 1. Exploratory data analysis with Pandas\\n"', '\\n.1', '<img align=\\center\\" src=\\"https://habrastorage.org/files/10c/15f/f3d/10c15ff3dcb14abdbabdac53fed6d825.jpg\\"  width=50% />\\n"', '\\n.2', '## Article outline\\n', '1. [Demonstration of main Pandas methods](#1.-Demonstration-of-main-Pandas-methods)\\n', '2. [First attempt at predicting telecom churn](#2.-First-attempt-at-predicting-telecom-churn)\\n', '3. [Assignments](#3.-Assignments)\\n', '4. [Useful resources](#4.-Useful-resources)]}', '{"cell_type":"markdown".1', 'id:"optional-comparative"', 'metadata:{"_uuid":"8000f32601aff93ebda3e8ca0baea376988a5649"', 'papermill:{"duration":0.043036', 'end_time:"2021-05-07T08:35:59.367136"', 'exception:false.2', 'start_time:"2021-05-07T08:35:59.3241"', 'status:"completed"}.2', 'tags:[]}.2', 'source:["## 1. Demonstration of main Pandas methods\\n"', 'Well... There are dozens of cool tutorials on Pandas and visual data analysis. If you are already familiar with these topics, you can wait for the 3rd article in the series, where we get into machine learning.  \\n', '\\n.3', '**[Pandas](http://pandas.pydata.org)** is a Python library that provides extensive means for data analysis. Data scientists often work with data stored in table formats like `.csv`, `.tsv`, or `.xlsx`. Pandas makes it very convenient to load, process, and analyze such tabular data using SQL-like queries. In conjunction with `Matplotlib` and `Seaborn`, `Pandas` provides a wide range of opportunities for visual analysis of tabular data.\\n', '\\n.4', 'The main data structures in `Pandas` are implemented with **Series** and **DataFrame** classes. The former is a one-dimensional indexed array of some fixed data type. The latter is a two-dimensional data structure - a table - where each column contains data of the same type. You can see it as a dictionary of `Series` instances. `DataFrames` are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.]}', '{"cell_type":"code"', 'execution_count:1', 'id:"supreme-beatles"', 'metadata:{"_uuid":"e855067a1d281ca6634772513ef918aa1c9224f4"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.459472Z"', 'iopub.status.busy:"2021-05-07T08:35:59.458289Z"', 'iopub.status.idle:"2021-05-07T08:35:59.462927Z"', 'shell.execute_reply:"2021-05-07T08:35:59.46356Z"}', 'papermill:{"duration":0.052221', 'end_time:"2021-05-07T08:35:59.463863"', 'exception:false.3', 'start_time:"2021-05-07T08:35:59.411642"', 'status:"completed"}.3', 'tags:[]}.3', 'outputs:[]', 'source:["import numpy as np\\n"', 'import pandas as pd\\n', '\\n.5', 'pd.set_option(\\display.precision\\"', ' 2)"]}', '{"cell_type":"markdown".2', 'id:"catholic-remainder"', 'metadata:{"_uuid":"e3ae8b8d09f0dd881831253957ca96d086038f7b"', 'papermill:{"duration":0.045851', 'end_time:"2021-05-07T08:35:59.553832"', 'exception:false.4', 'start_time:"2021-05-07T08:35:59.507981"', 'status:"completed"}.4', 'tags:[]}.4', 'source:["We\'ll demonstrate the main methods in action by analyzing a [dataset](https://bigml.com/user/francisco/gallery/dataset/5163ad540c0b5e5b22000383) on the churn rate of telecom operator clients. Let\'s read the data (using `read_csv`)', ' and take a look at the first 5 lines using the `head` method:"]}', '{"cell_type":"code".1', 'execution_count:2', 'id:"interesting-dodge"', 'metadata:{"_uuid":"f274f88e14b4df01f8f60bd8be5e0cea903a7dd7"', 'execution:{"iopub.execute_input":"2021-05-07T08:35:59.646729Z"', 'iopub.status.busy:"2021-05-07T08:35:59.645658Z"', 'iopub.status.idle:"2021-05-07T08:35:59.731091Z"', 'shell.execute_reply:"2021-05-07T08:35:59.731563Z"}', 'papermill:{"duration":0.13323', 'end_time:"2021-05-07T08:35:59.731738"', 'exception:false.5', 'start_time:"2021-05-07T08:35:59.598508"', 'status:"completed"}.5', 'tags:[]}.5', 'outputs:[{"data":{"text/html":["<div>\\n"', '<style scoped>\\n', '    .dataframe tbody tr th:only-of-type {\\n', '        vertical-align: middle;\\n', '    }\\n', '\\n.6', '    .dataframe tbody tr th {\\n', '        vertical-align: top;\\n', '    }\\n.1', '\\n.7', '    .dataframe thead th {\\n', '        text-align: right;\\n', '    }\\n.2', '</style>\\n', '<table border=\\1\\" class=\\"dataframe\\">\\n"', '  <thead>\\n', '    <tr style=\\text-align: right;\\">\\n"', '      <th></th>\\n', '      <th>State</th>\\n', '      <th>Account length</th>\\n', '      <th>Area code</th>\\n', '      <th>International plan</th>\\n', '      <th>Voice mail plan</th>\\n', '      <th>Number vmail messages</th>\\n', '      <th>Total day minutes</th>\\n', '      <th>Total day calls</th>\\n', '      <th>Total day charge</th>\\n', '      <th>Total eve minutes</th>\\n', '      <th>Total eve calls</th>\\n', '      <th>Total eve charge</th>\\n', '      <th>Total night minutes</th>\\n', '      <th>Total night calls</th>\\n', '      <th>Total night charge</th>\\n', '      <th>Total intl minutes</th>\\n', '      <th>Total intl calls</th>\\n', '      <th>Total intl charge</th>\\n', '      <th>Customer service calls</th>\\n', '      <th>Churn</th>\\n', '    </tr>\\n', '  </thead>\\n', '  <tbody>\\n', '    <tr>\\n', '      <th>0</th>\\n', '      <td>KS</td>\\n', '      <td>128</td>\\n', '      <td>415</td>\\n', '      <td>No</td>\\n', '      <td>Yes</td>\\n', '      <td>25</td>\\n', '      <td>265.1</td>\\n', '      <td>110</td>\\n', '      <td>45.07</td>\\n', '      <td>197.4</td>\\n', '      <td>99</td>\\n', '      <td>16.78</td>\\n', '      <td>244.7</td>\\n', '      <td>91</td>\\n', '      <td>11.01</td>\\n', '      <td>10.0</td>\\n', '      <td>3</td>\\n', '      <td>2.70</td>\\n', '      <td>1</td>\\n', '      <td>False</td>\\n', '    </tr>\\n.1', '    <tr>\\n.1', '      <th>1</th>\\n', '      <td>OH</td>\\n', '      <td>107</td>\\n', '      <td>415</td>\\n.1', '      <td>No</td>\\n.1', '      <td>Yes</td>\\n.1', '      <td>26</td>\\n', '      <td>161.6</td>\\n', '      <td>123</td>\\n', '      <td>27.47</td>\\n', '      <td>195.5</td>\\n', '      <td>103</td>\\n', '      <td>16.62</td>\\n', '      <td>254.4</td>\\n', '      <td>103</td>\\n.1', '      <td>11.45</td>\\n', '      <td>13.7</td>\\n', '      <td>3</td>\\n.1', '      <td>3.70</td>\\n', '      <td>1</td>\\n.1', '      <td>False</td>\\n.1', '    </tr>\\n.2', '    <tr>\\n.2', '      <th>2</th>\\n', '      <td>NJ</td>\\n', '      <td>137</td>\\n', '      <td>415</td>\\n.2', '      <td>No</td>\\n.2', '      <td>No</td>\\n.3', '      <td>0</td>\\n', '      <td>243.4</td>\\n', '      <td>114</td>\\n', '      <td>41.38</td>\\n', '      <td>121.2</td>\\n', '      <td>110</td>\\n.1', '      <td>10.30</td>\\n', '      <td>162.6</td>\\n', '      <td>104</td>\\n', '      <td>7.32</td>\\n', '      <td>12.2</td>\\n', '      <td>5</td>\\n', '      <td>3.29</td>\\n', '      <td>0</td>\\n.1', '      <td>False</td>\\n.2', '    </tr>\\n.3', '    <tr>\\n.3', '      <th>3</th>\\n', '      <td>OH</td>\\n.1', '      <td>84</td>\\n', '      <td>408</td>\\n', '      <td>Yes</td>\\n.2', '      <td>No</td>\\n.4', '      <td>0</td>\\n.2', '      <td>299.4</td>\\n', '      <td>71</td>\\n', '      <td>50.90</td>\\n', '      <td>61.9</td>\\n', '      <td>88</td>\\n', '      <td>5.26</td>\\n', '      <td>196.9</td>\\n', '      <td>89</td>\\n', '      <td>8.86</td>\\n', '      <td>6.6</td>\\n', '      <td>7</td>\\n', '      <td>1.78</td>\\n', '      <td>2</td>\\n', '      <td>False</td>\\n.3', '    </tr>\\n.4', '    <tr>\\n.4', '      <th>4</th>\\n', '      <td>OK</td>\\n', '      <td>75</td>\\n', '      <td>415</td>\\n.3', '      <td>Yes</td>\\n.3', '      <td>No</td>\\n.5', '      <td>0</td>\\n.3', '      <td>166.7</td>\\n', '      <td>113</td>\\n', '      <td>28.34</td>\\n', '      <td>148.3</td>\\n', '      <td>122</td>\\n', '      <td>12.61</td>\\n', '      <td>186.9</td>\\n', '      <td>121</td>\\n', '      <td>8.41</td>\\n', '      <td>10.1</td>\\n', '      <td>3</td>\\n.2', '      <td>2.73</td>\\n', '      <td>3</td>\\n.3', '      <td>False</td>\\n.4', '    </tr>\\n.5', '  </tbody>\\n', '</table>\\n', '</div>]', 'text/plain:["  State  Account length  Area code International plan Voice mail plan  \\\\\\n"', '0    KS             128        415                 No             Yes   \\n', '1    OH             107        415                 No             Yes   \\n', '2    NJ             137        415                 No              No   \\n', '3    OH              84        408                Yes              No   \\n', '4    OK              75        415                Yes              No   \\n', '\\n.8', '   Number vmail messages  Total day minutes  Total day calls  \\\\\\n', '0                     25              265.1              110   \\n', '1                     26              161.6              123   \\n', '2                      0              243.4              114   \\n', '3                      0              299.4               71   \\n', '4                      0              166.7              113   \\n', '\\n.9', '   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \\\\\\n', '0             45.07              197.4               99             16.78   \\n', '1             27.47              195.5              103             16.62   \\n', '2             41.38              121.2              110             10.30   \\n', '3             50.90               61.9               88              5.26   \\n', '4             28.34              148.3              122             12.61   \\n', '\\n.10', '   Total night minutes  Total night calls  Total night charge  \\\\\\n', '0                244.7                 91               11.01   \\n', '1                254.4                103               11.45   \\n', '2                162.6                104                7.32   \\n', '3                196.9                 89                8.86   \\n', '4                186.9                121                8.41   \\n', '\\n.11', '   Total intl minutes  Total intl calls  Total intl charge  \\\\\\n', '0                10.0                 3               2.70   \\n', '1                13.7                 3               3.70   \\n', '2                12.2                 5               3.29   \\n', '3                 6.6                 7               1.78   \\n', '4                10.1                 3               2.73   \\n', '\\n.12', '   Customer service calls  Churn  \\n', '0                       1  False  \\n', '1                       1  False  \\n', '2                       0  False  \\n', '3                       2  False  \\n', '4                       3  False  ]}', 'execution_count:2.1', 'metadata:{}', 'output_type:"execute_result"}]', 'source:["df = pd.read_csv(\\"../input/telecom_churn.csv\\")\\n"', 'df.head()]}', '{"cell_type":"markdown".3', 'id:"opposite-simulation"', 'metadata:{"_uuid":"a2f8fc5742d83ec5a110fa56fd967497013bec39"', 'papermill:{"duration":0.045163', 'end_time:"2021-05-07T08:35:59.823093"', 'exception:false.6', 'start_time:"2021-05-07T08:35:59.77793"', 'status:"completed"}.6', 'tags:[]}.6', 'source:["<details>\\n"', '<summary>About printing DataFrames in Jupyter notebooks</summary>\\n', '<p>\\n', 'In Jupyter notebooks, Pandas DataFrames are printed as these pretty tables seen above while `print(df.head())` is less nicely formatted.\\n', 'By default, Pandas displays 20 columns and 60 rows, so, if your DataFrame is bigger, use the `set_option` function as shown in the example below:\\n', '\\n.13', '```python\\n', "pd.set_option('display.max_columns', 100)\\n", "pd.set_option('display.max_rows', 100)\\n", '```\\n', '</p>\\n', '</details>\\n', '\\n.14', 'Recall that each row corresponds to one client, an **instance**, and columns are **features** of this instance.]}', '{"cell_type":"markdown".4', 'id:"going-wealth"', 'metadata:{"_uuid":"d1a98d3e208e59ad0825687ba732f32714fd5e5c"', 'papermill:{"duration":0.045703', 'end_time:"2021-05-07T08:35:59.91464"', 'exception:false.7', 'start_time:"2021-05-07T08:35:59.868937"', 'status:"completed"}.7', 'tags:[]}.7', 'source:["Let’s have a look at data dimensionality', ' feature names', ' and feature types."]}', '{"cell_type":"code".2', 'execution_count:3', 'id:"inside-stephen"', 'metadata:{"_uuid":"85347476c8a704b43ddc6b5ec54ac0059b2b740a"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.008269Z"', 'iopub.status.busy:"2021-05-07T08:36:00.007269Z"', 'iopub.status.idle:"2021-05-07T08:36:00.015284Z"', 'shell.execute_reply:"2021-05-07T08:36:00.014261Z"}', 'papermill:{"duration":0.055704', 'end_time:"2021-05-07T08:36:00.015548"', 'exception:false.8', 'start_time:"2021-05-07T08:35:59.959844"', 'status:"completed"}.8', 'tags:[]}.8', 'outputs:[{"name":"stdout"', 'output_type:"stream"', 'text:["(3333', ' 20)\\n"]}]', 'source:["print(df.shape)"]}', '{"cell_type":"markdown".5', 'id:"collaborative-memphis"', 'metadata:{"_uuid":"26e01159ec9dfc2634bbb3be4ccc3ec82c1b01e4"', 'papermill:{"duration":0.046317', 'end_time:"2021-05-07T08:36:00.108954"', 'exception:false.9', 'start_time:"2021-05-07T08:36:00.062637"', 'status:"completed"}.9', 'tags:[]}.9', 'source:["From the output', ' we can see that the table contains 3333 rows and 20 columns.\\n"', '\\n.15', "Now let's try printing out column names using `columns`:]}", '{"cell_type":"code".3', 'execution_count:4', 'id:"third-teach"', 'metadata:{"_uuid":"216df4e9a25d0baa8b506e1ec72df488d78367eb"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.205275Z"', 'iopub.status.busy:"2021-05-07T08:36:00.204509Z"', 'iopub.status.idle:"2021-05-07T08:36:00.208939Z"', 'shell.execute_reply:"2021-05-07T08:36:00.208036Z"}', 'papermill:{"duration":0.055147', 'end_time:"2021-05-07T08:36:00.209149"', 'exception:false.10', 'start_time:"2021-05-07T08:36:00.154002"', 'status:"completed"}.10', 'tags:[]}.10', 'outputs:[{"name":"stdout".1', 'output_type:"stream".1', 'text:["Index([\'State\'', " 'Account length'", " 'Area code'", " 'International plan'", '\\n"', "       'Voice mail plan', 'Number vmail messages', 'Total day minutes',\\n", "       'Total day calls', 'Total day charge', 'Total eve minutes',\\n", "       'Total eve calls', 'Total eve charge', 'Total night minutes',\\n", "       'Total night calls', 'Total night charge', 'Total intl minutes',\\n", "       'Total intl calls', 'Total intl charge', 'Customer service calls',\\n", "       'Churn'],\\n", "      dtype='object')\\n]}]", 'source:["print(df.columns)"]}', '{"cell_type":"markdown".6', 'id:"interim-indonesian"', 'metadata:{"_uuid":"60f8c02d4e9b4ef82f9721fc2fb274ca50e0d6e4"', 'papermill:{"duration":0.047694', 'end_time:"2021-05-07T08:36:00.30581"', 'exception:false.11', 'start_time:"2021-05-07T08:36:00.258116"', 'status:"completed"}.11', 'tags:[]}.11', 'source:["We can use the `info()` method to output some general information about the dataframe: "]}', '{"cell_type":"code".4', 'execution_count:5', 'id:"bored-moldova"', 'metadata:{"_uuid":"2bcfb060dcbda4fe1720eaf3c2e5c003a891dd77"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.40151Z"', 'iopub.status.busy:"2021-05-07T08:36:00.400861Z"', 'iopub.status.idle:"2021-05-07T08:36:00.422875Z"', 'shell.execute_reply:"2021-05-07T08:36:00.422342Z"}', 'papermill:{"duration":0.071027', 'end_time:"2021-05-07T08:36:00.423026"', 'exception:false.12', 'start_time:"2021-05-07T08:36:00.351999"', 'status:"completed"}.12', 'tags:[]}.12', 'outputs:[{"name":"stdout".2', 'output_type:"stream".2', 'text:["<class \'pandas.core.frame.DataFrame\'>\\n"', 'RangeIndex: 3333 entries, 0 to 3332\\n', 'Data columns (total 20 columns):\\n', ' #   Column                  Non-Null Count  Dtype  \\n', '---  ------                  --------------  -----  \\n', ' 0   State                   3333 non-null   object \\n', ' 1   Account length          3333 non-null   int64  \\n', ' 2   Area code               3333 non-null   int64  \\n', ' 3   International plan      3333 non-null   object \\n', ' 4   Voice mail plan         3333 non-null   object \\n', ' 5   Number vmail messages   3333 non-null   int64  \\n', ' 6   Total day minutes       3333 non-null   float64\\n', ' 7   Total day calls         3333 non-null   int64  \\n', ' 8   Total day charge        3333 non-null   float64\\n', ' 9   Total eve minutes       3333 non-null   float64\\n', ' 10  Total eve calls         3333 non-null   int64  \\n', ' 11  Total eve charge        3333 non-null   float64\\n', ' 12  Total night minutes     3333 non-null   float64\\n', ' 13  Total night calls       3333 non-null   int64  \\n', ' 14  Total night charge      3333 non-null   float64\\n', ' 15  Total intl minutes      3333 non-null   float64\\n', ' 16  Total intl calls        3333 non-null   int64  \\n', ' 17  Total intl charge       3333 non-null   float64\\n', ' 18  Customer service calls  3333 non-null   int64  \\n', ' 19  Churn                   3333 non-null   bool   \\n', 'dtypes: bool(1), float64(8), int64(8), object(3)\\n', 'memory usage: 498.1+ KB\\n', 'None\\n]}]', 'source:["print(df.info())"]}', '{"cell_type":"markdown".7', 'id:"desperate-leave"', 'metadata:{"_uuid":"6fac47f7e7bcf060164b1881d8e199973834cd38"', 'papermill:{"duration":0.045853', 'end_time:"2021-05-07T08:36:00.515119"', 'exception:false.13', 'start_time:"2021-05-07T08:36:00.469266"', 'status:"completed"}.13', 'tags:[]}.13', 'source:["`bool`', ' `int64`', ' `float64` and `object` are the data types of our features. We see that one feature is logical (`bool`)', ' 3 features are of type `object`', ' and 16 features are numeric. With this same method', ' we can easily see if there are any missing values. Here', ' there are none because each column contains 3333 observations', ' the same number of rows we saw before with `shape`.\\n"', '\\n.16', "We can **change the column type** with the `astype` method. Let's apply this method to the `Churn` feature to convert it into `int64`:]}", '{"cell_type":"code".5', 'execution_count:6', 'id:"proprietary-novelty"', 'metadata:{"_uuid":"16a0073ab34daea8192eb549c4c8a94e33b34a13"', 'execution:{"iopub.execute_input":"2021-05-07T08:36:00.62094Z"', 'iopub.status.busy:"2021-05-07T08:36:00.620112Z"', 'iopub.status.idle:"2021-05-07T08:36:00.623233Z"', 'shell.execute_reply:"2021-05-07T08:36:00.622698Z"}', 'papermill:{"duration":0.059473', 'end_time:"2021-05-07T08:36:00.623377"', 'exception:false.14', 'start_time:"2021-05-07T08:36:00.563904"', 'status:"completed"}.14', 'tags:[]}.14', 'outputs:[].1', 'source:["df[\\"Churn\\"] = df[\\"Churn\\"].astype(\\"int64\\")"]}', '{"cell_type":"markdown".8', 'id:"seventh-siemens"', 'metadata:{"_uuid":"11030a8bd020c6a3a04beb73531e9676160bcab8"', 'papermill:{"duration":0.045453', 'end_time:

In [ ]:
print("Shape:", df.shape)

Shape: (0, 4452)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Columns: 4452 entries, {"cells":[{"cell_type":"markdown" to nbformat_minor:5}
dtypes: object(4452)
memory usage: 132.0+ bytes

In [ ]:
df.describe()

,"{""cells"":[{""cell_type"":""markdown""","id:""stretch-davis""","metadata:{""_uuid"":""1752ce061957fd1ce93d2e4db9494b7b29da7935""","papermill:{""duration"":0.04692","end_time:""2021-05-07T08:35:59.190175""",exception:false,"start_time:""2021-05-07T08:35:59.143255""","status:""completed""}",tags:[]},"source:[""<center>\n""",...,"version:""2.3.2""}","kaggle:{""accelerator"":""none""","dataSources:[{""sourceType"":""datasetVersion""",sourceId:205932}],isInternetEnabled:false,"language:""python"".1","sourceType:""notebook""",isGpuEnabled:false}},nbformat:4,nbformat_minor:5}
count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
unique,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

{"cells":[{"cell_type":"markdown"                               0
id:"stretch-davis"                                              0
metadata:{"_uuid":"1752ce061957fd1ce93d2e4db9494b7b29da7935"    0
papermill:{"duration":0.04692                                   0
end_time:"2021-05-07T08:35:59.190175"                           0
                                                               ..
language:"python".1                                             0
sourceType:"notebook"                                           0
isGpuEnabled:false}}                                            0
nbformat:4                                                      0
nbformat_minor:5}                                               0
Length: 4452, dtype: int64

In [ ]:
import os

print(os.listdir('/content'))

['.config', '.ipynb_checkpoints', 'archive (1).zip', 'sample_data']

In [ ]:
import zipfile
import os

zip_path = '/content/archive (1).zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

print("Files extracted:")
print(os.listdir('/content/dataset'))

Files extracted:
['Telco_customer_churn.xlsx']

In [ ]:
import os

for root, dirs, files in os.walk('/content/dataset'):
    for file in files:
        print(os.path.join(root, file))

/content/dataset/Telco_customer_churn.xlsx

In [ ]:
import zipfile

zip_path = '/content/archive (1).zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    print("Files inside the ZIP:")
    for file in zip_ref.namelist():
        print(file)

Files inside the ZIP:
Telco_customer_churn.xlsx

In [ ]:
import zipfile

zip_path = '/content/archive (1).zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/dataset')

print("Extracted successfully!")

Extracted successfully!

In [ ]:
import os

print(os.listdir('/content/dataset'))

['Telco_customer_churn.xlsx']

In [ ]:
import pandas as pd

df = pd.read_excel('/content/dataset/Telco_customer_churn.xlsx')

In [ ]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [ ]:
print("Shape:", df.shape)

Shape: (7043, 33)

In [ ]:
print(df.columns.tolist())

['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [ ]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [ ]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [ ]:
missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    'Missing Values': missing_count,
    'Percentage': missing_percentage
})

missing_table

                   Missing Values  Percentage
CustomerID                      0    0.000000
Count                           0    0.000000
Country                         0    0.000000
State                           0    0.000000
City                            0    0.000000
Zip Code                        0    0.000000
Lat Long                        0    0.000000
Latitude                        0    0.000000
Longitude                       0    0.000000
Gender                          0    0.000000
Senior Citizen                  0    0.000000
Partner                         0    0.000000
Dependents                      0    0.000000
Tenure Months                   0    0.000000
Phone Service                   0    0.000000
Multiple Lines                  0    0.000000
Internet Service                0    0.000000
Online Security                 0    0.000000
Online Backup                   0    0.000000
Device Protection               0    0.000000
Tech Support                    0    0.000000
Streaming TV                    0    0.000000
Streaming Movies                0    0.000000
Contract                        0    0.000000
Paperless Billing               0    0.000000
Payment Method                  0    0.000000
Monthly Charges                 0    0.000000
Total Charges                   0    0.000000
Churn Label                     0    0.000000
Churn Value                     0    0.000000
Churn Score                     0    0.000000
CLTV                            0    0.000000
Churn Reason                 5174   73.463013

In [ ]:
df[df.isnull().any(axis=1)]

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
1869,7590-VHVEG,1,United States,California,Los Angeles,90001,"33.973616, -118.24902",33.973616,-118.249020,Female,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,27,3964,NaN
1870,5575-GNVDE,1,United States,California,Los Angeles,90002,"33.949255, -118.246978",33.949255,-118.246978,Male,...,One year,No,Mailed check,56.95,1889.5,No,0,61,3441,NaN
1871,7795-CFOCW,1,United States,California,Los Angeles,90004,"34.076259, -118.310715",34.076259,-118.310715,Male,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,66,4307,NaN
1872,1452-KIOVK,1,United States,California,Los Angeles,90007,"34.027337, -118.28515",34.027337,-118.285150,Male,...,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No,0,43,4459,NaN
1873,6713-OKOMC,1,United States,California,Los Angeles,90008,"34.008293, -118.346766",34.008293,-118.346766,Female,...,Month-to-month,No,Mailed check,29.75,301.9,No,0,51,2013,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [ ]:
(df == '').sum()

CustomerID           0
Count                0
Country              0
State                0
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
Churn Value          0
Churn Score          0
CLTV                 0
Churn Reason         0
dtype: int64

In [ ]:
(df == ' ').sum()

CustomerID            0
Count                 0
Country               0
State                 0
City                  0
Zip Code              0
Lat Long              0
Latitude              0
Longitude             0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Label           0
Churn Value           0
Churn Score           0
CLTV                  0
Churn Reason          0
dtype: int64

In [ ]:
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

In [ ]:
print(df.columns.tolist())

['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

In [ ]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [ ]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [ ]:
missing_count = df.isnull().sum()

missing_percentage = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    'Missing Values': missing_count,
    'Percentage': missing_percentage
})

missing_table

                   Missing Values  Percentage
CustomerID                      0    0.000000
Count                           0    0.000000
Country                         0    0.000000
State                           0    0.000000
City                            0    0.000000
Zip Code                        0    0.000000
Lat Long                        0    0.000000
Latitude                        0    0.000000
Longitude                       0    0.000000
Gender                          0    0.000000
Senior Citizen                  0    0.000000
Partner                         0    0.000000
Dependents                      0    0.000000
Tenure Months                   0    0.000000
Phone Service                   0    0.000000
Multiple Lines                  0    0.000000
Internet Service                0    0.000000
Online Security                 0    0.000000
Online Backup                   0    0.000000
Device Protection               0    0.000000
Tech Support                    0    0.000000
Streaming TV                    0    0.000000
Streaming Movies                0    0.000000
Contract                        0    0.000000
Paperless Billing               0    0.000000
Payment Method                  0    0.000000
Monthly Charges                 0    0.000000
Total Charges                   0    0.000000
Churn Label                     0    0.000000
Churn Value                     0    0.000000
Churn Score                     0    0.000000
CLTV                            0    0.000000
Churn Reason                 5174   73.463013

In [ ]:
missing_table[missing_table['Missing Values'] > 0]

              Missing Values  Percentage
Churn Reason            5174   73.463013

In [ ]:
df[df.isnull().any(axis=1)].head(20)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
1869,7590-VHVEG,1,United States,California,Los Angeles,90001,"33.973616, -118.24902",33.973616,-118.249020,Female,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,27,3964,NaN
1870,5575-GNVDE,1,United States,California,Los Angeles,90002,"33.949255, -118.246978",33.949255,-118.246978,Male,...,One year,No,Mailed check,56.95,1889.5,No,0,61,3441,NaN
1871,7795-CFOCW,1,United States,California,Los Angeles,90004,"34.076259, -118.310715",34.076259,-118.310715,Male,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,66,4307,NaN
1872,1452-KIOVK,1,United States,California,Los Angeles,90007,"34.027337, -118.28515",34.027337,-118.285150,Male,...,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No,0,43,4459,NaN
1873,6713-OKOMC,1,United States,California,Los Angeles,90008,"34.008293, -118.346766",34.008293,-118.346766,Female,...,Month-to-month,No,Mailed check,29.75,301.9,No,0,51,2013,NaN
1874,6388-TABGU,1,United States,California,Los Angeles,90011,"34.00709, -118.258681",34.007090,-118.258681,Male,...,One year,No,Bank transfer (automatic),56.15,3487.95,No,0,58,4529,NaN
1875,9763-GRSKD,1,United States,California,Los Angeles,90012,"34.065875, -118.238728",34.065875,-118.238728,Male,...,Month-to-month,Yes,Mailed check,49.95,587.45,No,0,76,5764,NaN
1876,7469-LKBCI,1,United States,California,Los Angeles,90013,"34.044639, -118.240413",34.044639,-118.240413,Male,...,Two year,No,Credit card (automatic),18.95,326.8,No,0,39,4726,NaN
1877,8091-TTVAX,1,United States,California,Los Angeles,90014,"34.043144, -118.251977",34.043144,-118.251977,Male,...,One year,No,Credit card (automatic),100.35,5681.1,No,0,71,6432,NaN
1878,5129-JLPIS,1,United States,California,Los Angeles,90016,"34.028331, -118.354338",34.028331,-118.354338,Male,...,Month-to-month,Yes,Electronic check,105.50,2686.05,No,0,75,5822,NaN
1879,3655-SNQYZ,1,United States,California,Los Angeles,90017,"34.052842, -118.264495",34.052842,-118.264495,Female,...,Two year,No,Credit card (automatic),113.25,7895.15,No,0,43,5141,NaN
1880,8191-XWSZG,1,United States,California,Los Angeles,90018,"34.028735, -118.317236",34.028735,-118.317236,Female,...,One year,No,Mailed check,20.65,1022.95,No,0,35,5186,NaN
1881,9959-WOFKT,1,United States,California,Los Angeles,90019,"34.049841, -118.33846",34.049841,-118.338460,Male,...,Two year,No,Bank transfer (automatic),106.70,7382.25,No,0,73,4479,NaN
1882,4183-MYFRB,1,United States,California,Los Angeles,90021,"34.029043, -118.239504",34.029043,-118.239504,Female,...,Month-to-month,Yes,Electronic check,90.05,1862.9,No,0,57,5982,NaN
1883,1680-VDCWW,1,United States,California,Los Angeles,90023,"34.017697, -118.200577",34.017697,-118.200577,Male,...,One year,No,Bank transfer (automatic),19.80,202.25,No,0,77,5279,NaN
1884,3638-WEABW,1,United States,California,Los Angeles,90025,"34.046174, -118.446333",34.046174,-118.446333,Female,...,Two year,Yes,Credit card (automatic),59.90,3505.1,No,0,53,6407,NaN
1885,6322-HRPFA,1,United States,California,Los Angeles,90026,"34.078991, -118.263804",34.078991,-118.263804,Male,...,Month-to-month,No,Credit card (automatic),59.60,2970.3,No,0,79,4986,NaN
1886,6865-JZNKO,1,United States,California,Los Angeles,90027,"34.127194, -118.295647",34.127194,-118.295647,Female,...,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.6,No,0,65,2725,NaN
1887,5248-YGIJN,1,United States,California,Los Angeles,90031,"34.085807, -118.206617",34.085807,-118.206617,Male,...,Two year,Yes,Credit card (automatic),90.25,6369.45,No,0,21,5974,NaN
1888,3841-NFECX,1,United States,California,Los Angeles,90033,"34.050198, -118.210946",34.050198,-118.210946,Female,...,Two year,Yes,Credit card (automatic),96.35,6766.95,No,0,38,5309,NaN

In [ ]:
(df == '').sum()

CustomerID           0
Count                0
Country              0
State                0
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
Churn Value          0
Churn Score          0
CLTV                 0
Churn Reason         0
dtype: int64

In [ ]:
(df == ' ').sum()

CustomerID            0
Count                 0
Country               0
State                 0
City                  0
Zip Code              0
Lat Long              0
Latitude              0
Longitude             0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Label           0
Churn Value           0
Churn Score           0
CLTV                  0
Churn Reason          0
dtype: int64

In [ ]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [ ]:
missing_count = df.isnull().sum()
missing_percentage = (missing_count / len(df)) * 100

missing_table = pd.DataFrame({
    'Missing Values': missing_count,
    'Percentage': missing_percentage
})

missing_table

                   Missing Values  Percentage
CustomerID                      0    0.000000
Count                           0    0.000000
Country                         0    0.000000
State                           0    0.000000
City                            0    0.000000
Zip Code                        0    0.000000
Lat Long                        0    0.000000
Latitude                        0    0.000000
Longitude                       0    0.000000
Gender                          0    0.000000
Senior Citizen                  0    0.000000
Partner                         0    0.000000
Dependents                      0    0.000000
Tenure Months                   0    0.000000
Phone Service                   0    0.000000
Multiple Lines                  0    0.000000
Internet Service                0    0.000000
Online Security                 0    0.000000
Online Backup                   0    0.000000
Device Protection               0    0.000000
Tech Support                    0    0.000000
Streaming TV                    0    0.000000
Streaming Movies                0    0.000000
Contract                        0    0.000000
Paperless Billing               0    0.000000
Payment Method                  0    0.000000
Monthly Charges                 0    0.000000
Total Charges                   0    0.000000
Churn Label                     0    0.000000
Churn Value                     0    0.000000
Churn Score                     0    0.000000
CLTV                            0    0.000000
Churn Reason                 5174   73.463013

In [ ]:
missing_table[missing_table['Missing Values'] > 0]

              Missing Values  Percentage
Churn Reason            5174   73.463013

In [ ]:
df[df.isnull().any(axis=1)].head(20)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
1869,7590-VHVEG,1,United States,California,Los Angeles,90001,"33.973616, -118.24902",33.973616,-118.249020,Female,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,27,3964,NaN
1870,5575-GNVDE,1,United States,California,Los Angeles,90002,"33.949255, -118.246978",33.949255,-118.246978,Male,...,One year,No,Mailed check,56.95,1889.5,No,0,61,3441,NaN
1871,7795-CFOCW,1,United States,California,Los Angeles,90004,"34.076259, -118.310715",34.076259,-118.310715,Male,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,66,4307,NaN
1872,1452-KIOVK,1,United States,California,Los Angeles,90007,"34.027337, -118.28515",34.027337,-118.285150,Male,...,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No,0,43,4459,NaN
1873,6713-OKOMC,1,United States,California,Los Angeles,90008,"34.008293, -118.346766",34.008293,-118.346766,Female,...,Month-to-month,No,Mailed check,29.75,301.9,No,0,51,2013,NaN
1874,6388-TABGU,1,United States,California,Los Angeles,90011,"34.00709, -118.258681",34.007090,-118.258681,Male,...,One year,No,Bank transfer (automatic),56.15,3487.95,No,0,58,4529,NaN
1875,9763-GRSKD,1,United States,California,Los Angeles,90012,"34.065875, -118.238728",34.065875,-118.238728,Male,...,Month-to-month,Yes,Mailed check,49.95,587.45,No,0,76,5764,NaN
1876,7469-LKBCI,1,United States,California,Los Angeles,90013,"34.044639, -118.240413",34.044639,-118.240413,Male,...,Two year,No,Credit card (automatic),18.95,326.8,No,0,39,4726,NaN
1877,8091-TTVAX,1,United States,California,Los Angeles,90014,"34.043144, -118.251977",34.043144,-118.251977,Male,...,One year,No,Credit card (automatic),100.35,5681.1,No,0,71,6432,NaN
1878,5129-JLPIS,1,United States,California,Los Angeles,90016,"34.028331, -118.354338",34.028331,-118.354338,Male,...,Month-to-month,Yes,Electronic check,105.50,2686.05,No,0,75,5822,NaN
1879,3655-SNQYZ,1,United States,California,Los Angeles,90017,"34.052842, -118.264495",34.052842,-118.264495,Female,...,Two year,No,Credit card (automatic),113.25,7895.15,No,0,43,5141,NaN
1880,8191-XWSZG,1,United States,California,Los Angeles,90018,"34.028735, -118.317236",34.028735,-118.317236,Female,...,One year,No,Mailed check,20.65,1022.95,No,0,35,5186,NaN
1881,9959-WOFKT,1,United States,California,Los Angeles,90019,"34.049841, -118.33846",34.049841,-118.338460,Male,...,Two year,No,Bank transfer (automatic),106.70,7382.25,No,0,73,4479,NaN
1882,4183-MYFRB,1,United States,California,Los Angeles,90021,"34.029043, -118.239504",34.029043,-118.239504,Female,...,Month-to-month,Yes,Electronic check,90.05,1862.9,No,0,57,5982,NaN
1883,1680-VDCWW,1,United States,California,Los Angeles,90023,"34.017697, -118.200577",34.017697,-118.200577,Male,...,One year,No,Bank transfer (automatic),19.80,202.25,No,0,77,5279,NaN
1884,3638-WEABW,1,United States,California,Los Angeles,90025,"34.046174, -118.446333",34.046174,-118.446333,Female,...,Two year,Yes,Credit card (automatic),59.90,3505.1,No,0,53,6407,NaN
1885,6322-HRPFA,1,United States,California,Los Angeles,90026,"34.078991, -118.263804",34.078991,-118.263804,Male,...,Month-to-month,No,Credit card (automatic),59.60,2970.3,No,0,79,4986,NaN
1886,6865-JZNKO,1,United States,California,Los Angeles,90027,"34.127194, -118.295647",34.127194,-118.295647,Female,...,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.6,No,0,65,2725,NaN
1887,5248-YGIJN,1,United States,California,Los Angeles,90031,"34.085807, -118.206617",34.085807,-118.206617,Male,...,Two year,Yes,Credit card (automatic),90.25,6369.45,No,0,21,5974,NaN
1888,3841-NFECX,1,United States,California,Los Angeles,90033,"34.050198, -118.210946",34.050198,-118.210946,Female,...,Two year,Yes,Credit card (automatic),96.35,6766.95,No,0,38,5309,NaN

In [ ]:
pd.crosstab(
    df['Churn Label'],
    df['Churn Reason'].isnull()
)

Churn Reason  False  True
Churn Label
No                0   5174
Yes            1869      0

In [ ]:
df[df['Churn Reason'].isnull()]['Churn Label'].value_counts()

Churn Label
No    5174
Name: count, dtype: int64

In [ ]:
(df == '').sum()

CustomerID           0
Count                0
Country              0
State                0
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
Churn Value          0
Churn Score          0
CLTV                 0
Churn Reason         0
dtype: int64

In [ ]:
(df == ' ').sum()

CustomerID            0
Count                 0
Country               0
State                 0
City                  0
Zip Code              0
Lat Long              0
Latitude              0
Longitude             0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Label           0
Churn Value           0
Churn Score           0
CLTV                  0
Churn Reason          0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
df[df.duplicated()].head()

Empty DataFrame
Columns: [CustomerID, Count, Country, State, City, Zip Code, Lat Long, Latitude, Longitude, Gender, Senior Citizen, Partner, Dependents, Tenure Months, Phone Service, Multiple Lines, Internet Service, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Payment Method, Monthly Charges, Total Charges, Churn Label, Churn Value, Churn Score, CLTV, Churn Reason]
Index: []

[0 rows x 33 columns]

In [ ]:
pd.crosstab(df['Churn Label'], df['Churn Reason'].isnull())

Churn Reason  False  True
Churn Label
No                0   5174
Yes            1869      0

In [ ]:
df[df['Churn Reason'].isnull()]['Churn Label'].value_counts()

Churn Label
No    5174
Name: count, dtype: int64

In [ ]:
(df == '').sum()

CustomerID           0
Count                0
Country              0
State                0
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
Churn Value          0
Churn Score          0
CLTV                 0
Churn Reason         0
dtype: int64

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
print("Duplicate Customer IDs:", df['CustomerID'].duplicated().sum())

Duplicate Customer IDs: 0

In [ ]:
print("Unique Customer IDs:", df['CustomerID'].nunique())
print("Total rows:", len(df))

Unique Customer IDs: 7043
Total rows: 7043

In [ ]:
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

In [ ]:
df.select_dtypes(include='number').columns.tolist()

['Count',
 'Zip Code',
 'Latitude',
 'Longitude',
 'Tenure Months',
 'Monthly Charges',
 'Churn Value',
 'Churn Score',
 'CLTV']

In [ ]:
df.select_dtypes(include='object').columns.tolist()

['CustomerID',
 'Country',
 'State',
 'City',
 'Lat Long',
 'Gender',
 'Senior Citizen',
 'Partner',
 'Dependents',
 'Phone Service',
 'Multiple Lines',
 'Internet Service',
 'Online Security',
 'Online Backup',
 'Device Protection',
 'Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Total Charges',
 'Churn Label',
 'Churn Reason']

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Count,7043.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Zip Code,7043.0,93521.964646,1865.794555,90001.000000,92102.000000,93552.000000,95351.000000,96161.000000
Latitude,7043.0,36.282441,2.455723,32.555828,34.030915,36.391777,38.224869,41.962127
Longitude,7043.0,-119.798880,2.157889,-124.301372,-121.815412,-119.730885,-118.043237,-114.192901
Tenure Months,7043.0,32.371149,24.559481,0.000000,9.000000,29.000000,55.000000,72.000000
Monthly Charges,7043.0,64.761692,30.090047,18.250000,35.500000,70.350000,89.850000,118.750000
Churn Value,7043.0,0.265370,0.441561,0.000000,0.000000,0.000000,1.000000,1.000000
Churn Score,7043.0,58.699418,21.525131,5.000000,40.000000,61.000000,75.000000,100.000000
CLTV,7043.0,4400.295755,1183.057152,2003.000000,3469.000000,4527.000000,5380.500000,6500.000000

In [ ]:
print("Duplicate Customer IDs:", df['CustomerID'].duplicated().sum())

Duplicate Customer IDs: 0

In [ ]:
print("Unique Customer IDs:", df['CustomerID'].nunique())
print("Total rows:", len(df))

Unique Customer IDs: 7043
Total rows: 7043

In [ ]:
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges         object
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Count,7043.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
Zip Code,7043.0,93521.964646,1865.794555,90001.000000,92102.000000,93552.000000,95351.000000,96161.000000
Latitude,7043.0,36.282441,2.455723,32.555828,34.030915,36.391777,38.224869,41.962127
Longitude,7043.0,-119.798880,2.157889,-124.301372,-121.815412,-119.730885,-118.043237,-114.192901
Tenure Months,7043.0,32.371149,24.559481,0.000000,9.000000,29.000000,55.000000,72.000000
Monthly Charges,7043.0,64.761692,30.090047,18.250000,35.500000,70.350000,89.850000,118.750000
Churn Value,7043.0,0.265370,0.441561,0.000000,0.000000,0.000000,1.000000,1.000000
Churn Score,7043.0,58.699418,21.525131,5.000000,40.000000,61.000000,75.000000,100.000000
CLTV,7043.0,4400.295755,1183.057152,2003.000000,3469.000000,4527.000000,5380.500000,6500.000000

In [ ]:
print(df['Total Charges'].head(10))

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: Total Charges, dtype: object

In [ ]:
print(df['Total Charges'].dtype)

object

In [ ]:
pd.to_numeric(df['Total Charges'], errors='coerce').isnull().sum()

np.int64(11)

In [ ]:
print(df['Count'].value_counts())

Count
1    7043
Name: count, dtype: int64

In [ ]:
print("Gender:")
print(df['Gender'].value_counts())

Gender:
Gender
Male      3555
Female    3488
Name: count, dtype: int64

In [ ]:
print("Senior Citizen:")
print(df['Senior Citizen'].value_counts())

Senior Citizen:
Senior Citizen
No     5901
Yes    1142
Name: count, dtype: int64

In [ ]:
print("Partner:")
print(df['Partner'].value_counts())

Partner:
Partner
No     3641
Yes    3402
Name: count, dtype: int64

In [ ]:
print("Dependents:")
print(df['Dependents'].value_counts())

Dependents:
Dependents
No     5416
Yes    1627
Name: count, dtype: int64

In [ ]:
for col in [
    'Phone Service',
    'Multiple Lines',
    'Internet Service',
    'Online Security',
    'Online Backup',
    'Device Protection',
    'Tech Support',
    'Streaming TV',
    'Streaming Movies'
]:
    print("\n", col)
    print(df[col].value_counts())

 Phone Service
Phone Service
Yes    6361
No      682
Name: count, dtype: int64

 Multiple Lines
Multiple Lines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

 Internet Service
Internet Service
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

 Online Security
Online Security
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

 Online Backup
Online Backup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

 Device Protection
Device Protection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

 Tech Support
Tech Support
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

 Streaming TV
Streaming TV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

 Streaming Movies
Streaming Movies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

In [ ]:
print(df['Total Charges'].head(10))

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: Total Charges, dtype: object

In [ ]:
print(df['Total Charges'].dtype)

object

In [ ]:
print(pd.to_numeric(df['Total Charges'], errors='coerce').isnull().sum())

11

In [ ]:
print(df['Count'].value_counts())

Count
1    7043
Name: count, dtype: int64

In [ ]:
print(df['Gender'].value_counts())
print(df['Senior Citizen'].value_counts())
print(df['Partner'].value_counts())
print(df['Dependents'].value_counts())

Gender
Male      3555
Female    3488
Name: count, dtype: int64
Senior Citizen
No     5901
Yes    1142
Name: count, dtype: int64
Partner
No     3641
Yes    3402
Name: count, dtype: int64
Dependents
No     5416
Yes    1627
Name: count, dtype: int64

In [ ]:
print(df['Total Charges'].head(10))

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
5     528.35
6      39.65
7      20.15
8    4749.15
9       30.2
Name: Total Charges, dtype: object

In [ ]:
print(df['Total Charges'].dtype)

object

In [ ]:
print(
    pd.to_numeric(df['Total Charges'], errors='coerce').isnull().sum()
)

11

In [ ]:
print(df['Count'].value_counts())

Count
1    7043
Name: count, dtype: int64

In [ ]:
numeric_total = pd.to_numeric(df['Total Charges'], errors='coerce')

problematic_total = df[
    numeric_total.isnull()
][['CustomerID', 'Tenure Months', 'Monthly Charges', 'Total Charges', 'Churn Label']]

problematic_total

      CustomerID  Tenure Months  Monthly Charges Total Charges Churn Label
2234  4472-LVYGI              0            52.55                        No
2438  3115-CZMZD              0            20.25                        No
2568  5709-LVOEQ              0            80.85                        No
2667  4367-NUYAO              0            25.75                        No
2856  1371-DWPAZ              0            56.05                        No
4331  7644-OMVMY              0            19.85                        No
4687  3213-VVOLG              0            25.35                        No
5104  2520-SGTTA              0            20.00                        No
5719  2923-ARZLG              0            19.70                        No
6772  4075-WKNIU              0            73.35                        No
6840  2775-SEFEE              0            61.90                        No

In [ ]:
for value in df.loc[numeric_total.isnull(), 'Total Charges']:
    print(repr(value))

' '
' '
' '
' '
' '
' '
' '
' '
' '
' '
' '

In [ ]:
problematic_total[['CustomerID', 'Tenure Months', 'Monthly Charges', 'Total Charges', 'Churn Label']]

      CustomerID  Tenure Months  Monthly Charges Total Charges Churn Label
2234  4472-LVYGI              0            52.55                        No
2438  3115-CZMZD              0            20.25                        No
2568  5709-LVOEQ              0            80.85                        No
2667  4367-NUYAO              0            25.75                        No
2856  1371-DWPAZ              0            56.05                        No
4331  7644-OMVMY              0            19.85                        No
4687  3213-VVOLG              0            25.35                        No
5104  2520-SGTTA              0            20.00                        No
5719  2923-ARZLG              0            19.70                        No
6772  4075-WKNIU              0            73.35                        No
6840  2775-SEFEE              0            61.90                        No

In [ ]:
numeric_total = pd.to_numeric(df['Total Charges'], errors='coerce')

problematic_total = df[
    numeric_total.isnull()
][['CustomerID', 'Tenure Months', 'Monthly Charges', 'Total Charges', 'Churn Label']]

problematic_total

      CustomerID  Tenure Months  Monthly Charges  Total Charges Churn Label
2234  4472-LVYGI              0            52.55            NaN          No
2438  3115-CZMZD              0            20.25            NaN          No
2568  5709-LVOEQ              0            80.85            NaN          No
2667  4367-NUYAO              0            25.75            NaN          No
2856  1371-DWPAZ              0            56.05            NaN          No
4331  7644-OMVMY              0            19.85            NaN          No
4687  3213-VVOLG              0            25.35            NaN          No
5104  2520-SGTTA              0            20.00            NaN          No
5719  2923-ARZLG              0            19.70            NaN          No
6772  4075-WKNIU              0            73.35            NaN          No
6840  2775-SEFEE              0            61.90            NaN          No

In [ ]:
for value in df.loc[numeric_total.isnull(), 'Total Charges']:
    print(repr(value))

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [ ]:
df['Total Charges'] = pd.to_numeric(
    df['Total Charges'],
    errors='coerce'
)

In [ ]:
print(df['Total Charges'].dtype)

float64

In [ ]:
print("Missing Total Charges:", df['Total Charges'].isnull().sum())

Missing Total Charges: 11

In [ ]:
df['Total Charges'] = df['Total Charges'].fillna(0)

In [ ]:
print("Missing Total Charges:", df['Total Charges'].isnull().sum())

Missing Total Charges: 0

In [ ]:
print(df['Total Charges'].dtype)

float64

In [ ]:
print("Unique values in Count:", df['Count'].nunique())
print("Standard deviation:", df['Count'].std())

Unique values in Count: 1
Standard deviation: 0.0

In [ ]:
numeric_cols = [
    'Tenure Months',
    'Monthly Charges',
    'Total Charges',
    'Churn Score',
    'CLTV'
]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    print(f"\n{col}")
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)
    print("Number of outliers:", len(outliers))

Tenure Months
Q1: 9.0
Q3: 55.0
IQR: 46.0
Lower Bound: -60.0
Upper Bound: 124.0
Number of outliers: 0

Monthly Charges
Q1: 35.5
Q3: 89.85
IQR: 54.349999999999994
Lower Bound: -46.02499999999999
Upper Bound: 171.375
Number of outliers: 0

Total Charges
Q1: 398.55
Q3: 3786.6
IQR: 3388.0499999999997
Lower Bound: -4683.525
Upper Bound: 8868.675
Number of outliers: 0

Churn Score
Q1: 40.0
Q3: 75.0
IQR: 35.0
Lower Bound: -12.5
Upper Bound: 127.5
Number of outliers: 0

CLTV
Q1: 3469.0
Q3: 5380.5
IQR: 1911.5
Lower Bound: 601.75
Upper Bound: 8247.75
Number of outliers: 0

In [ ]:
categorical_cols = [
    'Phone Service',
    'Multiple Lines',
    'Internet Service',
    'Online Security',
    'Online Backup',
    'Device Protection',
    'Tech Support',
    'Streaming TV',
    'Streaming Movies',
    'Contract',
    'Paperless Billing',
    'Payment Method',
    'Churn Label'
]

for col in categorical_cols:
    print("\n" + "=" * 50)
    print(col)
    print(df[col].value_counts())

==================================================
Phone Service
Phone Service
Yes    6361
No      682
Name: count, dtype: int64

==================================================
Multiple Lines
Multiple Lines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

==================================================
Internet Service
Internet Service
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

==================================================
Online Security
Online Security
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

==================================================
Online Backup
Online Backup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

==================================================
Device Protection
Device Protection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

==================================================
Tech Support
Tech Support
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

==================================================
Streaming TV
Streaming TV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

==================================================
Streaming Movies
Streaming Movies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

==================================================
Contract
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

==================================================
Paperless Billing
Paperless Billing
Yes    4171
No     2872
Name: count, dtype: int64

==================================================
Payment Method
Payment Method
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

==================================================
Churn Label
Churn Label
No     5174
Yes    1869
Name: count, dtype: int64

In [ ]:
print("Total rows:", len(df))
print("Unique Customer IDs:", df['CustomerID'].nunique())
print("Duplicate Customer IDs:", df['CustomerID'].duplicated().sum())

Total rows: 7043
Unique Customer IDs: 7043
Duplicate Customer IDs: 0

In [ ]:
print("Negative Tenure:", (df['Tenure Months'] < 0).sum())
print("Negative Monthly Charges:", (df['Monthly Charges'] < 0).sum())
print("Negative Total Charges:", (df['Total Charges'] < 0).sum())
print("Invalid Churn Value:", (~df['Churn Value'].isin([0, 1])).sum())
print("Invalid Churn Score:", ((df['Churn Score'] < 0) | (df['Churn Score'] > 100)).sum())
print("Negative CLTV:", (df['CLTV'] < 0).sum())

Negative Tenure: 0
Negative Monthly Charges: 0
Negative Total Charges: 0
Invalid Churn Value: 0
Invalid Churn Score: 0
Negative CLTV: 0

In [ ]:
print(
    pd.crosstab(
        df['Churn Label'],
        df['Churn Value']
    )
)

Churn Value     0     1
Churn Label
No           5174     0
Yes             0  1869

In [ ]:
print("Total rows:", len(df))
print("Unique Customer IDs:", df['CustomerID'].nunique())
print("Duplicate Customer IDs:", df['CustomerID'].duplicated().sum())

Total rows: 7043
Unique Customer IDs: 7043
Duplicate Customer IDs: 0

In [ ]:
print("Negative Tenure:", (df['Tenure Months'] < 0).sum())
print("Negative Monthly Charges:", (df['Monthly Charges'] < 0).sum())
print("Negative Total Charges:", (df['Total Charges'] < 0).sum())
print("Invalid Churn Value:", (~df['Churn Value'].isin([0, 1])).sum())
print("Invalid Churn Score:", ((df['Churn Score'] < 0) | (df['Churn Score'] > 100)).sum())
print("Negative CLTV:", (df['CLTV'] < 0).sum())

Negative Tenure: 0
Negative Monthly Charges: 0
Negative Total Charges: 0
Invalid Churn Value: 0
Invalid Churn Score: 0
Negative CLTV: 0

In [ ]:
df = df.drop(columns=['Count'])

In [ ]:
print(df.shape)
print('Count' in df.columns)

(7043, 32)
False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Country            7043 non-null   object
 2   State              7043 non-null   object
 3   City               7043 non-null   object
 4   Zip Code           7043 non-null   int64
 5   Lat Long           7043 non-null   object
 6   Latitude           7043 non-null   float64
 7   Longitude          7043 non-null   float64
 8   Gender             7043 non-null   object
 9   Senior Citizen     7043 non-null   object
 10  Partner            7043 non-null   object
 11  Dependents         7043 non-null   object
 12  Tenure Months      7043 non-null   int64
 13  Phone Service      7043 non-null   object
 14  Multiple Lines     7043 non-null   object
 15  Internet Service   7043 non-null   object
 16  Online Security    7043 non-null   object
 17  Online Backup      7043 non-null   object
 18  Device Protection  7043 non-null   object
 19  Tech Support       7043 non-null   object
 20  Streaming TV       7043 non-null   object
 21  Streaming Movies   7043 non-null   object
 22  Contract           7043 non-null   object
 23  Paperless Billing  7043 non-null   object
 24  Payment Method     7043 non-null   object
 25  Monthly Charges    7043 non-null   float64
 26  Total Charges      7043 non-null   float64
 27  Churn Label        7043 non-null   object
 28  Churn Value        7043 non-null   int64
 29  Churn Score        7043 non-null   int64
 30  CLTV               7043 non-null   int64
 31  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(5), object(23)
memory usage: 1.7+ MB

In [ ]:
print("Total missing values:", df.isnull().sum().sum())
print("Total duplicate rows:", df.duplicated().sum())

Total missing values: 5174
Total duplicate rows: 0

In [ ]:
print(df['Total Charges'].describe())

count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: Total Charges, dtype: float64

In [ ]:
print(df['Total Charges'].isnull().sum())

0

In [ ]:
print(df.columns.tolist())

['CustomerID', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

In [ ]:
df = df.drop(columns=[
    'CustomerID',
    'Country',
    'State',
    'Lat Long'
])

In [ ]:
print(df.shape)
print(df.columns.tolist())

(7043, 28)
['City', 'Zip Code', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason']

In [ ]:
cleaned_df = df.copy()

print("Cleaned dataset shape:", cleaned_df.shape)

Cleaned dataset shape: (7043, 28)

In [ ]:
model_df = cleaned_df.drop(columns=['Churn Label', 'Churn Reason'])

In [ ]:
print(model_df.shape)
print(model_df.columns.tolist())

(7043, 26)
['City', 'Zip Code', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charges', 'Total Charges', 'Churn Value', 'Churn Score', 'CLTV']

In [ ]:
categorical_cols = model_df.select_dtypes(include='object').columns.tolist()

print("Categorical columns:")
print(categorical_cols)

Categorical columns:
['City', 'Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security', 'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV', 'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method']

In [ ]:
model_df_encoded = pd.get_dummies(
    model_df,
    columns=categorical_cols,
    drop_first=True
)

In [ ]:
print("Before encoding:", model_df.shape)
print("After encoding:", model_df_encoded.shape)

Before encoding: (7043, 26)
After encoding: (7043, 1164)

In [ ]:
model_df_encoded = model_df_encoded.astype(int)

In [ ]:
print(model_df_encoded.dtypes.value_counts())

int64    1164
Name: count, dtype: int64

In [ ]:
print("Object columns remaining:",
      model_df_encoded.select_dtypes(include='object').columns.tolist())

Object columns remaining: []

In [ ]:
print(model_df_encoded.head())

   Zip Code  Latitude  Longitude  Tenure Months  Monthly Charges  \
0     90003        33       -118              2               53
1     90005        34       -118              2               70
2     90006        34       -118              8               99
3     90010        34       -118             28              104
4     90015        34       -118             49              103

   Total Charges  Churn Value  Churn Score  CLTV  City_Acton  ...  \
0            108            1           86  3239           0  ...
1            151            1           67  2701           0  ...
2            820            1           86  5372           0  ...
3           3046            1           84  5003           0  ...
4           5036            1           89  5340           0  ...

   Streaming TV_No internet service  Streaming TV_Yes  \
0                                 0                 0
1                                 0                 0
2                                 0                 1
3                                 0                 1
4                                 0                 1

   Streaming Movies_No internet service  Streaming Movies_Yes  \
0                                     0                     0
1                                     0                     0
2                                     0                     1
3                                     0                     1
4                                     0                     1

   Contract_One year  Contract_Two year  Paperless Billing_Yes  \
0                  0                  0                      1
1                  0                  0                      1
2                  0                  0                      1
3                  0                  0                      1
4                  0                  0                      1

   Payment Method_Credit card (automatic)  Payment Method_Electronic check  \
0                                       0                                0
1                                       0                                1
2                                       0                                1
3                                       0                                1
4                                       0                                0

   Payment Method_Mailed check
0                            1
1                            0
2                            0
3                            0
4                            0

[5 rows x 1164 columns]

In [ ]:
print(model_df_encoded.shape)

(7043, 1164)

In [ ]:
print("Total missing values:",
      model_df_encoded.isnull().sum().sum())

Total missing values: 0

In [ ]:
print("Duplicate rows:",
      model_df_encoded.duplicated().sum())

Duplicate rows: 0

In [ ]:
print(model_df_encoded.dtypes.value_counts())

int64    1164
Name: count, dtype: int64

In [ ]:
print("Object columns:",
      model_df_encoded.select_dtypes(include='object').columns.tolist())

Object columns: []

In [ ]:
print("Churn Value" in model_df_encoded.columns)

True

In [ ]:
print(model_df_encoded.describe().T.head(20))

                    count          mean          std      min      25%  \
Zip Code           7043.0  93521.964646  1865.794555  90001.0  92102.0
Latitude           7043.0     35.775096     2.469345     32.0     34.0
Longitude          7043.0   -119.338918     2.158186   -124.0   -121.0
Tenure Months      7043.0     32.371149    24.559481      0.0      9.0
Monthly Charges    7043.0     64.295897    30.092727     18.0     35.0
Total Charges      7043.0   2279.265086  2266.790864      0.0    398.0
Churn Value        7043.0      0.265370     0.441561      0.0      0.0
Churn Score        7043.0     58.699418    21.525131      5.0     40.0
CLTV               7043.0   4400.295755  1183.057152   2003.0   3469.0
City_Acton         7043.0      0.000568     0.023826      0.0      0.0
City_Adelanto      7043.0      0.000710     0.026637      0.0      0.0
City_Adin          7043.0      0.000568     0.023826      0.0      0.0
City_Agoura Hills  7043.0      0.000710     0.026637      0.0      0.0
City_Aguanga       7043.0      0.000568     0.023826      0.0      0.0
City_Ahwahnee      7043.0      0.000568     0.023826      0.0      0.0
City_Alameda       7043.0      0.001136     0.033686      0.0      0.0
City_Alamo         7043.0      0.000568     0.023826      0.0      0.0
City_Albany        7043.0      0.000568     0.023826      0.0      0.0
City_Albion        7043.0      0.000568     0.023826      0.0      0.0
City_Alderpoint    7043.0      0.000568     0.023826      0.0      0.0

                       50%      75%      max
Zip Code           93552.0  95351.0  96161.0
Latitude              36.0     38.0     41.0
Longitude           -119.0   -118.0   -114.0
Tenure Months         29.0     55.0     72.0
Monthly Charges       70.0     89.0    118.0
Total Charges       1394.0   3786.5   8684.0
Churn Value            0.0      1.0      1.0
Churn Score           61.0     75.0    100.0
CLTV                4527.0   5380.5   6500.0
City_Acton             0.0      0.0      1.0
City_Adelanto          0.0      0.0      1.0
City_Adin              0.0      0.0      1.0
City_Agoura Hills      0.0      0.0      1.0
City_Aguanga           0.0      0.0      1.0
City_Ahwahnee          0.0      0.0      1.0
City_Alameda           0.0      0.0      1.0
City_Alamo             0.0      0.0      1.0
City_Albany            0.0      0.0      1.0
City_Albion            0.0      0.0      1.0
City_Alderpoint        0.0      0.0      1.0

In [ ]:
print("Shape:", model_df_encoded.shape)

print("Missing values:",
      model_df_encoded.isnull().sum().sum())

print("Duplicate rows:",
      model_df_encoded.duplicated().sum())

print("Object columns:",
      model_df_encoded.select_dtypes(include='object').columns.tolist())

print("Infinite values:",
      np.isinf(model_df_encoded.select_dtypes(include=np.number)).sum().sum())

Shape: (7043, 1164)
Missing values: 0
Duplicate rows: 0
Object columns: []
Infinite values: 0

In [ ]:
cleaned_df.to_csv('/content/telco_churn_cleaned.csv', index=False)

In [ ]:
model_df_encoded.to_csv('/content/telco_churn_preprocessed.csv', index=False)

In [ ]:
import os

print("Cleaned file exists:",
      os.path.exists('/content/telco_churn_cleaned.csv'))

print("Preprocessed file exists:",
      os.path.exists('/content/telco_churn_preprocessed.csv'))

Cleaned file exists: True
Preprocessed file exists: True

In [ ]:
print("========== BEFORE CLEANING ==========")
print("Rows:", 7043)
print("Columns:", 33)

print("\n========== AFTER CLEANING ==========")
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

print("\n========== AFTER ENCODING ==========")
print("Rows:", model_df_encoded.shape[0])
print("Columns:", model_df_encoded.shape[1])

========== BEFORE CLEANING ==========
Rows: 7043
Columns: 33

========== AFTER CLEANING ==========
Rows: 7043
Columns: 28

========== AFTER ENCODING ==========
Rows: 7043
Columns: 1164

In [ ]:
print(df.shape)

(7043, 28)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Latitude           7043 non-null   float64
 3   Longitude          7043 non-null   float64
 4   Gender             7043 non-null   object
 5   Senior Citizen     7043 non-null   object
 6   Partner            7043 non-null   object
 7   Dependents         7043 non-null   object
 8   Tenure Months      7043 non-null   int64
 9   Phone Service      7043 non-null   object
 10  Multiple Lines     7043 non-null   object
 11  Internet Service   7043 non-null   object
 12  Online Security    7043 non-null   object
 13  Online Backup      7043 non-null   object
 14  Device Protection  7043 non-null   object
 15  Tech Support       7043 non-null   object
 16  Streaming TV       7043 non-null   object
 17  Streaming Movies   7043 non-null   object
 18  Contract           7043 non-null   object
 19  Paperless Billing  7043 non-null   object
 20  Payment Method     7043 non-null   object
 21  Monthly Charges    7043 non-null   float64
 22  Total Charges      7043 non-null   float64
 23  Churn Label        7043 non-null   object
 24  Churn Value        7043 non-null   int64
 25  Churn Score        7043 non-null   int64
 26  CLTV               7043 non-null   int64
 27  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(5), object(19)
memory usage: 1.5+ MB

In [ ]:
missing_table = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': (df.isnull().sum() / len(df)) * 100
})

missing_table

                   Missing Values  Percentage
City                            0    0.000000
Zip Code                        0    0.000000
Latitude                        0    0.000000
Longitude                       0    0.000000
Gender                          0    0.000000
Senior Citizen                  0    0.000000
Partner                         0    0.000000
Dependents                      0    0.000000
Tenure Months                   0    0.000000
Phone Service                   0    0.000000
Multiple Lines                  0    0.000000
Internet Service                0    0.000000
Online Security                 0    0.000000
Online Backup                   0    0.000000
Device Protection               0    0.000000
Tech Support                    0    0.000000
Streaming TV                    0    0.000000
Streaming Movies                0    0.000000
Contract                        0    0.000000
Paperless Billing               0    0.000000
Payment Method                  0    0.000000
Monthly Charges                 0    0.000000
Total Charges                   0    0.000000
Churn Label                     0    0.000000
Churn Value                     0    0.000000
Churn Score                     0    0.000000
CLTV                            0    0.000000
Churn Reason                 5174   73.463013

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
print(df['Gender'].value_counts())

Gender
Male      3555
Female    3488
Name: count, dtype: int64

In [ ]:
print(df['Contract'].value_counts())

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

In [ ]:
pd.crosstab(df['Churn Label'], df['Churn Value'])

Churn Value     0     1
Churn Label
No           5174     0
Yes             0  1869

In [ ]:
df['Total Charges'] = pd.to_numeric(
    df['Total Charges'],
    errors='coerce'
)

In [ ]:
categorical_cols = model_df.select_dtypes(
    include='object'
).columns.tolist()

model_df_encoded = pd.get_dummies(
    model_df,
    columns=categorical_cols,
    drop_first=True
)

model_df_encoded = model_df_encoded.astype(int)

In [ ]:
print("Shape:", model_df_encoded.shape)

print(
    "Missing values:",
    model_df_encoded.isnull().sum().sum()
)

print(
    "Duplicate rows:",
    model_df_encoded.duplicated().sum()
)

print(
    "Object columns:",
    model_df_encoded.select_dtypes(
        include='object'
    ).columns.tolist()
)

Shape: (7043, 1164)
Missing values: 0
Duplicate rows: 0
Object columns: []